// Algi V0 — the genome-first model option inside the Scion provider.
//
// Scion downloads a 3.35 GB general base to make about six typed calls against
// a knowledge index that already ships in the app. Algi V0 keeps the same
// provider, compiler, grader, and exporters and replaces only the recall step:
// the course skeleton is composed from the uploaded source and the genome
// instead of generated by a parametric model.
//
// The consequence is not "a smaller model" — it is NO model download, so the
// first artifact arrives without a multi-gigabyte wait. Kept as a leaf module
// beside publicScionIdentity so the landing page can render the option without
// pulling the composer.
// No import from publicScionIdentity: that module lists this one among the
// provider's options, and a cycle would break the landing page's lazy chunk.
export const ALGI_MODEL_ID = 'algi-v0';
export const ALGI_MODEL_NAME = 'Algi V0';
export const ALGI_PROVIDER_ID = 'public';
export const ALGI_DOWNLOAD_BYTES = 0;
export const ALGI_MAX_COMPLETION_TOKENS = 2400;

/** True when a request should be answered from the genome instead of a model. */
export function isAlgiModel(modelId) {
  return String(modelId || '') === ALGI_MODEL_ID;
}

/**
 * Algi has no sampling runtime, so sending compiled prose back through its
 * provider route cannot produce a voice rewrite. Keep that zero-model promise
 * explicit instead of recording a fake call, fallback, or estimated cost.
 */
export function supportsModelVoicePass(modelId) {
  return !isAlgiModel(modelId);
}

/** Algi composes one course-wide enrichment batch; sampled models keep their own limit. */
export function resolveAlgiEnrichmentBatchSize(provider, modelId, lessonCount, fallback = 1) {
  if (provider !== ALGI_PROVIDER_ID || !isAlgiModel(modelId)) return Math.max(1, Number(fallback) || 1);
  return Math.max(1, Number(lessonCount) || 1);
}

export function algiModelOption() {
  return {
    id: ALGI_MODEL_ID,
    name: ALGI_MODEL_NAME,
    created: 0,
    maxInputTokens: 8192,
    maxOutputTokens: ALGI_MAX_COMPLETION_TOKENS,
    source: 'genome-local',
    // No weights are downloaded or executed, so no sampling capability is
    // claimed. Structured output is composed, not sampled.
    capabilities: {
      jsonMode: false,
      jsonSchema: false,
      toolCalling: false,
      streaming: false,
      temperature: false,
    },
  };
}
