import { APP_VERSION } from './appVersion.js';

export const CURRENT_RELEASE = {
  version: APP_VERSION,
  date: 'June 20, 2026',
  title: 'Source Proof Fallback: source-backed exports cannot go silent',
  landingTitle: 'Source Proof Fallback',
  highlights: [
    'A fresh deployed v0.15.40 Genetics and Society ZIP audit regraded at 99/A with export verified, but proved a source-proof handoff regression: the digest reported CurriculumV1 repair plus five open resources while the ZIP omitted `sourceLedger`, sourceRef coverage, and `SOURCE_REPORT.md`.',
    'Package export now falls back to a CourseIR-derived source-proof graph only when source-backed pipeline state expects proof and the export graph has no source rows, so the ZIP ships an explicit review receipt instead of going silent.',
    'The fallback is intentionally not trusted bibliography: URL/DOI/license-free CourseIR rows are quarantined as `sourceReviewRows`, while `SOURCE_REPORT.md` explains the review status and atom sourceRef coverage.',
    'Focused exporter regression coverage recreates the live missing-ledger shape without weakening source-thinness, review-row, or fake-citation grader checks.',
  ],
  landingHighlights: [
    'Source-backed exports always include a source proof report.',
    'Review-only CourseIR proof stays visibly quarantined.',
    'The source-quality bar stays strict.',
  ],
  proof: {
    contract: 'release-contracts/v0.15.41.json',
    roadmap: 'docs/V0.15.41_SOURCE_PROOF_FALLBACK_ROADMAP.md',
    auditCommand: 'npm run audit:release-history',
  },
};

export { APP_VERSION };

export const CURRENT_RELEASE_CHANGELOG = {
  version: CURRENT_RELEASE.version,
  date: CURRENT_RELEASE.date,
  title: CURRENT_RELEASE.title,
  highlights: CURRENT_RELEASE.highlights,
};

export const HISTORICAL_RELEASE_CHANGELOGS = [
  {
    version: '0.15.40',
    date: 'June 20, 2026',
    title: 'Source Relevance and Slide Polish Guard: generic background sources stop entering genetics packages',
    highlights: [
      'A fresh deployed v0.15.39 Genetics and Society ZIP audit regraded at 98/A with export verified, but still exposed a real slide-deck P1 and a semantically wrong source row: Wikipedia “Driving under the influence” was attached to genetics concepts.',
      'Slide deck compilation now runs one final export pass over every slide bullet, so long authored bullets keep terminal punctuation while short labels and relationship-arrow concept pairs stay intentionally bare.',
      'The source-finder discipline-anchor gate now applies to background providers such as Wikipedia in genetics/genomics contexts, so generic environment/testing/background rows cannot win by matching broad query words alone.',
      'Focused regression coverage pins both live failure shapes without weakening the quality grader or hiding the remaining source-license review findings.',
    ],
  },
  {
    version: '0.15.39',
    date: 'June 20, 2026',
    title: 'Course FAQ Evidence Firewall: compact artifact lists stop becoming source evidence',
    highlights: [
      'A fresh deployed v0.15.38 Genetics and Society ZIP audit improved to Quality 97/A with export verified, but still exposed a real P1: compact resource-label prose such as “slide decks 2. quiz bank 3” survived into Course FAQ evidence and anchor examples.',
      'The Course Map repair pass now preserves array and numbered-list boundaries when checking supporting resources, so compact artifact-resource lists are repaired before they can become lesson evidence.',
      'The blueprint compiler no longer elects prompt artifact labels or compact artifact-label runs as throughline evidence packets for normal disciplinary courses.',
      'Course FAQ rendering now uses a safe lesson/source evidence cue for focus answers, material-review answers, and anchor contrasts when stale metadata still contains artifact labels.',
      'Regression coverage pins the exported v0.15.38 failure shape without weakening the quality grader or hiding the remaining source-license and source-ledger findings.',
    ],
  },
  {
    version: '0.15.38',
    date: 'June 20, 2026',
    title: 'Artifact Resource Firewall: deliverable labels stop leaking into Course FAQ concepts',
    highlights: [
      'A fresh deployed v0.15.37 Genetics and Society audit exposed a real P0: single deliverable labels such as “slide decks” survived as supporting resources and then appeared in Course FAQ answers as if they were lesson concepts.',
      'The Course Map repair pass now treats exact single supporting-resource cells that are requested deliverable labels as prompt-artifact contamination for non-instructional-design courses.',
      'The repair keeps the v0.15.12 precision exception for legitimate “worked examples” resources while blocking labels like slide decks, quiz bank, study guides, and course FAQ.',
      'Regression coverage now proves the repaired Course FAQ no longer says “Strong work uses slide decks” for the live Genetics failure shape.',
      'The emitted run digest now waits for finalize-time quality grading, so a package blocked by quality P0s no longer logs a misleading ready `[CM][DIGEST]`.',
    ],
  },
  {
    version: '0.15.37',
    date: 'June 20, 2026',
    title: 'Source Finder Relevance Gate: generic Crossref hits stop masquerading as genetics sources',
    highlights: [
      'A fresh deployed v0.15.36 Genetics and Society audit proved the source-ledger bridge worked: the ZIP now carried five source rows and local regrade removed the previous source-thinness P1.',
      'The same audit exposed the next real defect: broad Crossref metadata hits such as building-environment standards and geotechnical-testing standards could attach to genetics lessons by matching only generic words like “environment” or “testing.”',
      'Source-finder relevance now requires academic metadata hits for genetics/genomics courses to carry a genetics anchor in the source itself, so generic Crossref/OpenAlex/ERIC rows cannot win by one shared generic term.',
      'Focused regression coverage recreates the exact failure shape and proves genetics-specific Crossref rows survive while generic environment/testing traps are rejected.',
    ],
  },
  {
    version: '0.15.36',
    date: 'June 20, 2026',
    title: 'Source Ledger Bridge: retrieved sources survive native re-derivation',
    highlights: [
      'Two fresh deployed v0.15.35 EduTool.dev audits regraded at 96/A and 98/A because retrieved OpenAlex/source-finder resources were visible in the run digest but the exported source ledger still collapsed to one ambiguous OpenLibrary row.',
      'Native stable-id re-derivation now preserves unmatched source-backed resources, including session-linked OpenAlex and source-finder rows, instead of dropping them when a later map repair rewrites the visible resource cell.',
      'The source ledger can now recover concept-linked academic rows directly from the source-finder mini-shard when graph resource cells are sparse, so export proof does not depend on a fragile rendered citation surviving every UI pass.',
      'The source-thinness gate stays armed: this release bridges retrieved rows into the bibliography proof, but it does not weaken the grader or claim that every CurriculumV1 atom is semantically source-relevant yet.',
    ],
  },
  {
    version: '0.15.35',
    date: 'June 20, 2026',
    title: 'Source Thinness Gate: sourceRef coverage can no longer hide one-row proof',
    highlights: [
      'A fresh deployed v0.15.34 EduTool.dev AI Governance audit proved source reports now ship, but the ZIP regraded at 98/A once the grader caught 56 sourceRef-covered atoms relying on one thin OpenLibrary metadata row.',
      'The source-ledger grader now treats complete-looking sourceRef coverage as insufficient when many atoms rest on one thin, review-required bibliography row.',
      'The ZIP audit helper no longer treats AI-governance model-card/model-documentation policy language as missing data-science lab assets unless actual notebook/IPYNB or local lab-asset evidence is present.',
      'The release keeps the 100/100 target honest: the audited v0.15.34 package is progress, not complete research-brain quality, and still regrades below 100 because source proof is thin.',
    ],
  },
  {
    version: '0.15.34',
    date: 'June 20, 2026',
    title: 'Knowledge Resource Handoff: source-backed graph survives export',
    highlights: [
      'A fresh deployed v0.15.33 EduTool.dev AI Governance audit exported successfully, but the ZIP regraded at 98/A because the package lost source-ledger proof while the console digest reported 7 retrieved open resources.',
      'AppFlow now adopts generated CourseGraphs synchronously before the knowledge-backbone display-map repair can trigger stale graph re-derivation.',
      'Native stable-id re-derivation now preserves matched verified resource metadata such as provider, URL, license, origin, source-finder shard, and reading-list decisions instead of degrading citations into generic syllabus rows.',
      'A focused regression proves an OpenAlex resource survives render -> derive -> match with its source metadata and section resourceRefs intact.',
      'The quality bar stays honest: packages still receive a source-proof finding when no trusted source rows or sourceRef coverage reach the ZIP.',
    ],
  },
  {
    version: '0.15.33',
    date: 'June 20, 2026',
    title: 'Assessment Echo Guard: syllabus and policy checks stop blocking AI governance exports',
    highlights: [
      'A fresh deployed v0.15.32 EduTool.dev AI Governance audit reached 99/A but blocked export on a syllabus model-card heuristic and exposed `Assessment: 1. Assessment` echoes in syllabus fields.',
      'Assessment registry titles are de-duplicated before they feed student artifacts, assessment anchors, grading provenance, syllabus schedules, and important dates.',
      'Embedded weight-evidence snippets strip repeated numbered assessment titles instead of preserving raw `Title: 1. Title` chains.',
      'The non-ML lab-assets validator still blocks Jupyter/IPYNB/starter-notebook leakage, but no longer blocks model-card language for explicit AI governance/model-documentation courses.',
      'Targeted compiler and pedagogical-validator regressions pin the AI Governance and Policy Memo failure classes.',
    ],
  },
  {
    version: '0.15.32',
    date: 'June 20, 2026',
    title: 'Slide Note Echo Guard: course-title prefixes stop leaking into deck text',
    highlights: [
      'A fresh deployed v0.15.31 EduTool.dev Environmental Justice audit regraded the ZIP at 99/A with two P2s: source-review rows stayed honest review debt, and a Policy memo slide deck rendered a deterministic `X: X` echo.',
      'Title-slide context now uses the lesson concept phrase instead of `courseName: phrase`, removing `Course: Topic` echoes from visible title slides.',
      'Numbered assessment echoes such as `Assessment: 1. Assessment` are de-duplicated before becoming slide artifacts.',
      'Title-slide speaker-note anchors strip long course-name prefixes before quoted `Use "..."` guidance.',
      'An Environmental Justice / Policy memo regression pins the exported slide surface, including titles, bullets, visuals, visual plans, and speaker notes.',
    ],
  },
  {
    version: '0.15.31',
    date: 'June 20, 2026',
    title: 'Source Review Truth: fallback rows stop posing as bibliography',
    highlights: [
      'A fresh deployed v0.15.30 EduTool.dev Sociology audit regraded the ZIP at 99/A with two real P2s: CourseIR fallback `SL1` was exported as ambiguous bibliography proof, and one assignment rendered `Academic Integrity: Integrity...`.',
      'Finish-package results now carry the current CourseGraph back to the export panel, and ZIP downloads use that finish graph instead of a potentially stale prop.',
      'CourseIR fallback rows without URL/DOI/license proof are quarantined into `sourceReviewRows` and `SOURCE_REPORT.md` review notes instead of polluting `sourceLedger` as trusted bibliography.',
      'The deep grader still flags review-only source rows; the fix changes the evidence class, not the standard.',
      'Assignment academic-integrity prose no longer begins with `Integrity for...`, removing the deterministic `X: X` echo exposed in the audited Research Methods assignment brief.',
    ],
  },
  {
    version: '0.15.30',
    date: 'June 20, 2026',
    title: 'ZIP Source Graph Handoff: downloaded proof matches the badge',
    highlights: [
      'A fresh deployed v0.15.29 EduTool.dev Sociology audit proved fake fallback source rows were gone, but exposed a new truth mismatch: the live badge graded graph-backed source proof while the downloaded ZIP lost that graph.',
      'The workspace export panel now receives the live CourseGraph from AppFlow and passes it into `downloadCourseMaterialsZip`, so header and side-panel downloads assemble the same source-ledger package the finish grade evaluated.',
      '`SOURCE_REPORT.md`, `sourceLedger`, `sourceLedgerSummary`, and CourseIR/sourceRef proof no longer disappear only on the final ZIP download path.',
      'Focused regression coverage pins the one-verb header ZIP route so it keeps using the export panel guards while preserving graph-backed source proof.',
      'The quality bar stays honest: packages without real exported source proof still receive the source-proof P1 instead of a fake or stale green badge.',
    ],
  },
  {
    version: '0.15.29',
    date: 'June 20, 2026',
    title: 'Source Ledger Fallback Guard: fake receipts stop shipping',
    highlights: [
      'A fresh deployed v0.15.28 EduTool.dev Sociology audit proved source reports now ship, but also exposed polluted proof: `SOURCE_REPORT.md` listed package labels and generic placeholders as source rows.',
      'Course Map and syllabus resource fallbacks now pass through a source-candidate guard before they can become normalized source-ledger rows.',
      'Package labels such as course map, lesson plans, slide decks, rubrics, study guides, and generic placeholder resource sentences are rejected instead of exported as fake citations.',
      'Real fallback receipts still survive when they carry source evidence such as OpenStax/OpenAlex/Open Library/ERIC hints, URL, DOI, Creative Commons/open-access license text, or recognizable academic/OER source signals.',
      'The quality bar stays honest: absent source proof remains a source-proof problem, while focused source-ledger and ZIP-export regressions pin the audited Sociology failure class.',
    ],
  },
  {
    version: '0.15.28',
    date: 'June 20, 2026',
    title: 'Source Proof Export Truth: ZIP receipts match the run',
    highlights: [
      'A fresh deployed v0.15.27 EduTool.dev Sociology audit exposed a real proof mismatch: the browser finalizer reported source-truth quality at 87/B while the downloaded ZIP regraded at 99/A because source receipts were missing.',
      'Source-backed exports now recover source-ledger rows from deterministic Course Map supporting-resource and reading cells when the live CourseGraph handoff is sparse.',
      'The source normalizer now extracts embedded URLs, DOI values, provider hints, and Creative Commons/open-access license labels from rendered resource text instead of dropping those receipts.',
      'Package export merges CourseIR/CourseGraph rows with Course Map fallback rows before writing `SOURCE_REPORT.md`, `sourceLedger`, and `sourceLedgerSummary`.',
      'The deep grader now arms source-ledger checks from pipeline evidence as well as exported proof, so source-backed packages with no receipts receive a P1 honesty finding instead of a clean score.',
    ],
  },
  {
    version: '0.15.27',
    date: 'June 20, 2026',
    title: 'Research Source Ledger: curriculum atoms cite trusted source rows',
    highlights: [
      'CourseIR source ledger rows now normalize title, authors, URL/DOI, license, provider, concept links, checkedAt, access status, trust level, and license-review flags instead of carrying only loose provenance text.',
      'CurriculumV1 now treats worked examples and assessment prompts as sourceRef-bearing atoms alongside outcomes, activities, factual anchors, and rubric criteria; missing or dangling refs repair before compile and reject direct-provider acceptance.',
      'CourseIR projection now feeds source-ledger labels into supporting resources, records atom-level sourceRef coverage on the graph and pipeline proof, and keeps deterministic compile provider calls at zero.',
      'Downloaded packages now include `sourceLedger`, `sourceLedgerSummary`, `courseIR.sourceRefCoverage`, and a root `SOURCE_REPORT.md` bibliography/coverage receipt.',
      'The deep grader now self-arms on source-ledger proof and flags fake or incomplete source rows, missing sourceRefs, dangling sourceRefs, inaccessible source rows, unsupported factual claims, and ambiguous licenses without weakening existing quality gates.',
    ],
  },
  {
    version: '0.15.26',
    date: 'June 20, 2026',
    title: 'Compiler Texture Pass 3: policy and participation tails stop repeating',
    highlights: [
      'A fresh deployed EduTool.dev Intro Psychology ZIP/log audit on v0.15.25 proved Pass 2 shipped, but the live UI and packaged QUALITY_REPORT still reported 99/A because texture stayed at 93/100.',
      'The remaining evidence was deterministic compiler prose in slide agenda notes, assignment integrity policy, and discussion participation-access language, not export failure or provider retry drift.',
      'The compiler now varies assignment integrity statements, agenda slide evidence/misconception/criterion cues, and discussion alternative-participation wording across lessons.',
      'Focused regression coverage now checks assignment briefs and discussion prompts against the exact v0.15.25 repeated shingles alongside the prior slide, lesson-plan, study-guide, and FAQ surfaces.',
      'The release keeps the quality bar honest: no grader weakening, no score inflation, and no live 100/100 claim until the next deployed EduTool.dev audit proves it.',
    ],
  },
  {
    version: '0.15.25',
    date: 'June 20, 2026',
    title: 'Compiler Texture Pass 2: support-surface tails stop repeating',
    highlights: [
      'A fresh deployed EduTool.dev Intro Psychology ZIP/log audit on v0.15.24 proved the first compiler-texture fix shipped, but the package still regraded 99/A because whole-package texture stayed at 93/100.',
      'The new evidence was narrower and deterministic: slide decks, lesson plans, study guides, and Course FAQ reused stock compiler support-surface phrases while export, retries, findings, and voice-surface texture were clean.',
      'The compiler now varies the slide-deck example-misconception note, deep kernel conference note, study-guide kernel-fact hint, and checkpoint-response quality-focus phrase across lessons.',
      'Focused regression coverage now checks all four audited surfaces against the exact repeated shingles from the v0.15.24 downloaded package instead of only the first slide/lesson-plan texture tails.',
      'The release keeps the quality bar honest: no grader weakening, no score inflation, and no live 100/100 claim until the next deployed EduTool.dev audit proves it.',
    ],
  },
  {
    version: '0.15.24',
    date: 'June 20, 2026',
    title: 'Compiler Texture: repeated teaching tails stop costing package quality',
    highlights: [
      'A fresh deployed EduTool.dev Intro Psychology ZIP/log audit on v0.15.23 confirmed the in-class assessment fix worked: no P0/P1/P2 findings, clean ZIP structure, and the remaining 99/A came only from texture 93 repeated compiler prose.',
      'The compiler now varies the default peer-evidence practice move and lecture-exam retrieval cycle across lessons, preventing long shared tails from stamping every slide deck.',
      'Slide speaker notes and deep misconception exit-ticket notes now rotate the audited activity/example/closure anchors while preserving the same classroom intent and genome-linked correction substance.',
      'Voice-pass disclosure now says voice-surface texture, and the manifest records `textureScope: "voice-surfaces"`, so a scoped rewrite self-check no longer implies whole-package texture was repaired.',
      'Focused regression coverage pins the audited four-lesson Psychology lecture/exam shape and rejects the repeated tails that appeared in the v0.15.23 downloaded ZIP evidence.',
    ],
  },
  {
    version: '0.15.23',
    date: 'June 19, 2026',
    title: 'Assessment Reconciliation: in-class checks stop blocking perfect packages',
    highlights: [
      'A fresh deployed EduTool.dev Intro Psychology ZIP/log audit on v0.15.22 produced a complete package at 99/A only because eight classroom checks were treated as missing standalone artifacts.',
      'The assessment registry now classifies quick evidence checks, exit tickets, and practice responses as zero-weight in-class checks, while explicit percentage-weighted evidence checks remain graded artifacts.',
      'The package finalizer no longer emits an assessment-reconciliation caveat for true in-class checks, because those are satisfied by lesson plans rather than assignment, quiz, or rubric files.',
      'Missing formal artifacts still stay visible: high-stakes exam/final/portfolio language continues to become a warning, and low-stakes unknown assessment promises still produce the digest info line.',
      'Focused regressions pin the exact audited Psychology shape so the next generated package can reach 100/100 when its only uncovered rows are in-class activities.',
    ],
  },
  {
    version: '0.15.22',
    date: 'June 19, 2026',
    title: 'EduTool Audit Tightening: modality labels stop becoming concepts',
    highlights: [
      'A live EduTool.dev Intro Psychology ZIP/log audit now has a saved evidence report tying the release to real package output instead of synthetic inspection alone.',
      'Native Pass A now treats section titles as subject-matter topics only and drops modality-only labels such as lecture, lab, workshop, discussion, seminar, and recitation before they become Course Map rows.',
      'The psychology genome now links broad Intro Psych lesson titles such as learning, memory, and cognitive bias to existing anchored OpenStax kernels without lowering the resolver threshold globally.',
      'The research-methods shard is restored as a foundry-owned manifest shard, so research ethics and informed-consent lessons can load and link through the same hash-pinned genome path as other disciplines.',
      'Focused regressions pin the exact audited Intro Psych topic mix, proving it infers psychology plus research-methods and no longer reports a 0/4 genome-link run for those broad lessons.',
    ],
  },
  {
    version: '0.15.21',
    date: 'June 19, 2026',
    title: 'CourseIR Source Trace: curriculum atoms become genome-linked',
    highlights: [
      'CourseIR lesson outcomes, learner activities, and rubric criteria now require `sourceRefs` that resolve to the source ledger before the object counts as a valid curriculum brain.',
      'Compiler repair can restore missing or dangling atom source refs for explicit CourseIR input before deterministic rendering, recording `added-atom-source-refs` proof instead of hiding the repair.',
      'Direct provider CourseIR acceptance now rejects source-ref repair, so native authoring cannot fall back to unlinked prose while claiming direct structured authorship.',
      'CourseIR validation stats now count source-linked outcomes, activities, and rubric criteria, giving graders and package reports a concrete traceability signal.',
      'Legacy course-map normalization now emits source-linked outcomes, activities, factual anchors, and rubric criteria against the normalized source ledger.',
    ],
  },
  {
    version: '0.15.20',
    date: 'June 19, 2026',
    title: 'CourseIR Rubric Atoms: assessment criteria become validated brain structure',
    highlights: [
      'CourseIR assessments now carry first-class `rubricCriteria[]` atoms with descriptions, concept links, outcome links, and performance levels before an assessment can count as fully structured.',
      'Compiler repair can synthesize missing rubric criteria for explicit CourseIR input before deterministic rendering, recording `added-assessment-rubric-criteria` proof instead of hiding the repair.',
      'Direct provider CourseIR acceptance now rejects repaired or level-less rubric structure, so bare rubric strings no longer masquerade as a complete curriculum brain.',
      'CourseIR projection feeds rubric criteria into enrichment surfaces and the lesson completeness ledger now counts assessment rubric coverage.',
      'Native authoring remains compatible with the stricter CourseIR rubric contract, preserving the current path while direct CourseIR gets a sharper assessment-quality boundary.',
    ],
  },
  {
    version: '0.15.19',
    date: 'June 19, 2026',
    title: 'CourseIR Activity Genome: learner work becomes validated atoms',
    highlights: [
      'CourseIR lessons now carry first-class `outcomes[]` and `activities[]` atoms, each linked to concept ids and assessment ids before a lesson can count as complete.',
      'Compiler repair can still synthesize missing outcome/activity atoms for explicit CourseIR input before deterministic rendering, but the repair is recorded as `added-lesson-outcomes` / `added-lesson-activities` proof.',
      'Direct provider CourseIR acceptance now rejects prose-derived or repaired learner-work structure instead of letting native/objective/activity prose masquerade as a better curriculum brain.',
      'CourseIR projection uses authored activity atoms first when building course-map and enrichment surfaces, with deterministic derivation only supplementing or repairing older inputs.',
      'Native authoring remains compatible with the stricter CourseIR contract, so the current path keeps working while the direct CourseIR path gets a sharper quality boundary.',
    ],
  },
  {
    version: '0.15.18',
    date: 'June 19, 2026',
    title: 'CourseIR Repair Boundary: synthetic fixes stop counting as direct authoring',
    highlights: [
      'Direct provider CourseIR acceptance now fails when the returned CourseIR needed deterministic structural repair before validation, so one broad assessment for many lessons no longer masquerades as a fully authored curriculum brain.',
      'Compiler repair remains available for explicit CourseIR inputs: under-assessed structures can still expand to lesson-level assessments before deterministic rendering, with `repairedBeforeCompile` proof intact.',
      'The direct-authoring acceptance result now carries `repairedBeforeAcceptance`, making the fallback reason auditable instead of hiding a synthetic fix behind an accepted direct path.',
      'Regression coverage pins the boundary: repaired broad-assessment CourseIR is rejected for direct provider authoring while the same CourseIR still compiles with zero provider calls after repair.',
      'This narrows the path toward the real CurriculumV1 source of truth: models must author dense atoms themselves, while compiler repair is an explicit safety net before DOCX/PPTX output.',
    ],
  },
  {
    version: '0.15.17',
    date: 'June 19, 2026',
    title: 'CourseIR Direct Authoring: whole-course brain can own the compile',
    highlights: [
      'Direct CourseIR authoring now runs before native skeleton authoring when native mode is active and the selected model has enough context/output capacity for one whole-course CurriculumV1 object.',
      'Thin CourseIR is rejected even when structural JSON validation passes: accepted direct CourseIR must cover lessons with concepts, assessments, factual anchors, worked examples, constraints, and misconception correctives.',
      'Accepted CourseIR crosses from generation to deliverables as a single-use, course-keyed source object and compiles through CurriculumV1 projection without native Pass B provider calls.',
      'Downloaded package manifests can now disclose `courseIR.directAuthoring` proof separately from `courseIR.nativeAssembly` repair/projection proof.',
      'The release roadmap names the quality boundary clearly: genome-linked content is important, but the better curriculum brain is the dense validated CourseIR object plus compiler expansion, not a shallow giant-call JSON blob.',
    ],
  },
  {
    version: '0.15.16',
    date: 'June 19, 2026',
    title: 'CurriculumV1 Source Truth: healthy native plans compile from the brain',
    highlights: [
      'Healthy native assembly now validates the Pass A/Pass B wire map as CourseIR and projects the compile graph from CurriculumV1 before any deliverable compiler runs.',
      'Native source surfaces stay honest during that projection: real instructor readings remain readings, real resources remain resources, and CourseIR support notes no longer inflate the resource registry.',
      'The run digest/log trail now marks healthy native generation as a CurriculumV1 source graph, while repaired sparse plans keep their explicit CurriculumV1 repair disclosure.',
      'Downloaded package manifests now include `courseIR.nativeAssembly` proof for healthy native CourseIR projection, including whether later map edits occurred after projection.',
      'Course-map edits on CurriculumV1-projected native graphs keep stable native entity ids, preserving the B4 re-derive behavior while the graph remains marked as CourseIR-authored.',
    ],
  },
  {
    version: '0.15.15',
    date: 'June 19, 2026',
    title: 'CurriculumV1 Native Repair: sparse native plans stop falling back',
    highlights: [
      'CurriculumV1 now carries more of the course brain: constraints, prerequisite concept links, source ledger repair, lesson concept repair, and under-assessed course repair are validated before graph compilation.',
      'Native assembly no longer treats the common one-assessment skeleton as an automatic prose fallback. Recoverable sparse native graphs repair through CurriculumV1 first, return a CourseIR-backed graph, and log the repair explicitly.',
      'Downloaded package manifests now carry slim CourseIR/native-repair proof metadata, so exported ZIPs can disclose whether a package came from a repaired curriculum graph instead of hiding the recovery path.',
      'The genome gained an introductory research-methods shard and coverage tests, improving the grounding layer for hypothesis, variables, operational definitions, causation, and informed-consent courses.',
      'The proof is broad because this touches compiler architecture: targeted native/CourseIR/package/genome tests, full unit suite, constitution audit, build, bundle budget, and all 40 gold samples pass locally.',
    ],
  },
  {
    version: '0.15.14',
    date: 'June 19, 2026',
    title: 'Teacher-Ready Constitution: package quality gets a fast standard',
    highlights: [
      'The Teacher-Ready Package Constitution now defines seven non-negotiable obligations for generated packages: identity coherence, complete structure, assessment coverage, caveat honesty, discipline fit, artifact substance, and clear handoff.',
      'A machine-readable `quality-constitution/v1.json` contract names `npm run audit:constitution` as the fast package-safety release gate while keeping `npm run audit:gold` for scheduled broad regression and large compiler/generator changes.',
      'Five canonical fixtures now probe distinct structural risks: a clean package, hidden digest caveat, missing assessment artifact, wrong-discipline assets, and a green handoff with thin artifacts.',
      'The deterministic constitution audit evaluates those fixtures without provider calls and writes both JSON and Markdown reports under `verification-output/constitution-audit/`.',
      'Focused Vitest coverage pins the npm script wiring, contract policy, fixture set, and report output so narrow quality releases no longer need the full 40-sample gold corpus as default proof.',
    ],
  },
  {
    version: '0.15.13',
    date: 'June 19, 2026',
    title: 'Native Fallback Audit Truth: digest caveats reach generated packages',
    highlights: [
      'A live EduTool.dev Microeconomics package exposed a report-truth gap: the run digest recorded a native-authoring prose fallback, but the shipped package report only showed the assessment-coverage observation.',
      'The deep package grader now converts digest `pipeline.nativeAuthoring` prose fallbacks into scored P2 honesty findings, including the evidence string from the run digest.',
      'When the package manifest omits that native-authoring fallback, the quality report names the missing disclosure explicitly instead of letting the ZIP look cleaner than the run that created it.',
      'Regression coverage now builds a package with a digest-only native fallback and regrades the downloaded-ZIP path, proving the report surfaces the caveat and the manifest omission.',
      'The release keeps the CourseIR one-call compiler architecture as carry-forward work; this patch improves the current audit/report layer without changing provider-call routing.',
    ],
  },
  {
    version: '0.15.12',
    date: 'June 19, 2026',
    title: 'Prompt Artifact Precision: worked examples stop false-positive grading',
    highlights: [
      'A live EduTool.dev astronomy run proved the v0.15.11 Course Map firewall held, but also exposed an overbroad grader P1 when “worked examples” appeared as an ordinary supporting resource.',
      'Prompt artifact detection now keeps “worked examples” suspicious as a numbered lesson topic while allowing normal FAQ and resource phrasing such as worked examples, readings, or activity sheets.',
      'The stricter P0 behavior remains intact for multi-label Course Map leakage, so requested deliverables still cannot masquerade as lesson concepts.',
      'Regression coverage now includes the exact astronomy false-positive shape alongside the environmental-science contamination blocker and instructional-design exemption.',
      'The release keeps the CourseIR one-call architecture as carry-forward work; this patch tunes the shipped grader without changing the generation architecture.',
    ],
  },
  {
    version: '0.15.11',
    date: 'June 19, 2026',
    title: 'Prompt Artifact Firewall: requested deliverables stop becoming lesson concepts',
    highlights: [
      'A live EduTool.dev environmental-science run exposed prompt artifact contamination: “lesson plans,” “slide decks,” “assignment briefs,” and related requested deliverables became course-map topics while the package still reported 99/A.',
      'Course-map readiness repair now treats prompt artifact labels as invalid topic candidates for normal disciplinary courses and rewrites contaminated cells from the real lesson topic before compilation.',
      'The Crucible grader now scores prompt artifact contamination as a package defect, with multi-label course-map contamination becoming a P0 so a polished ZIP cannot hide unusable lesson concepts behind an A badge.',
      'Regression coverage pins both layers: the repair test proves contaminated environmental-science sections return to ecosystems, and the grader test proves the old ZIP shape regrades as unsafe instead of clean.',
      'The release keeps the CourseIR one-call architecture as carry-forward work; this patch narrows the current shipped path while CourseIR remains behind proof gates.',
    ],
  },
  {
    version: '0.15.10',
    date: 'June 19, 2026',
    title: 'CourseIR Architecture: one canonical course brain before compilation',
    highlights: [
      'CourseIR v1 now normalizes and validates a dense course source of truth with source-ledger, concept, lesson, assessment, repair-path, and coverage-ledger checks.',
      'The dense prompt contract asks providers for semantic atoms instead of final artifact prose: lesson kernels, concept graph, factual anchors, examples, and assessment blueprints.',
      'The model-capacity planner chooses one whole-course IR call when safe, or the fewest sharded IR calls when output caps, reserve, reliability, or cost require it.',
      'The CurriculumOS compiler facade accepts CourseIR and deterministically renders selected package artifacts through the existing CourseGraph/blueprint path with zero provider calls.',
      'CourseIR proof metadata can ride into package assembly, while the default product flip still waits for flagged 5-, 8-, and 15-lesson quality/cost comparisons.',
    ],
  },
  {
    version: '0.15.9',
    date: 'June 19, 2026',
    title: 'Provider Call Rightsizing: the course package stops paying for avoidable batches',
    highlights: [
      'Native Pass B now batches by real model output capacity, so long-output structured models can author a normal 15-lesson course in one enrichment call.',
      'Native recovery stops after a no-progress retry instead of spending again on the same missing lesson set.',
      'The voice pass sends the selected eight-surface set in one fixed 4k-output call.',
      'GPT-5.4/GPT-5.5 context metadata is current, and model-limit lookup prefers the most specific model prefix.',
    ],
  },
  {
    version: '0.15.8',
    date: 'June 19, 2026',
    title: 'EduTool Audit Truth: generated packages stop looking cleaner than they are',
    highlights: [
      'Package quality now scores run-digest caveats from real EduTool exports, including partial enrichment/template fallback and course-map assessment coverage gaps.',
      'Saved DevTools logs are scoped to the current run digest before honesty checks, so stale rows from earlier generations cannot create false genome-count P1s.',
      'The finished-package overview surfaces P0/P1 quality caveats beside the grade with a compact review chip that opens the detailed quality report.',
      'Assignment Brief DOCX exports render an explicit handoff note for lessons with no standalone submitted assignment instead of shipping a title-only file.',
      'The grader now flags title-only assignment briefs as substantive P1 package defects, using the live Introduction to CS Lesson 14 failure shape as regression coverage.',
      'Slide decks collapse course-title echo chains in title bullets and speaker notes, preventing "course: course" repetition in first-lesson decks.',
    ],
  },
  {
    version: '0.15.7',
    date: 'June 17, 2026',
    title: 'Finished Package Surface: ready means handoff, not audit work',
    highlights: [
      'Ready Course Map now opens to a finished-package overview instead of the dense editable table, with Edit course map one click away.',
      'The overview summarizes lesson count, material readiness, quality/texture, safe repairs, export checks, and material shortcuts while the side panel remains the single package export surface.',
      'The agent panel enters compact ready mode: project-brief strip, working-set panel, opener buttons, and old queue cards are hidden while the package receipt and chat input remain available.',
      'Finished-package material cards jump directly to generated artifact tabs, while the Course Map card opens the editable map only when requested.',
      'The v0.15.7 release contract and tests pin the overwhelmed-ready-state fix separately from v0.15.6 backend/grader truth work.',
      'Browser smoke remains part of the proof path so the download handoff is exercised in a real workspace before the release is trusted.',
    ],
  },
  {
    version: '0.15.6',
    date: 'June 17, 2026',
    title: 'Classroom Truth: coverage, texture, and ready states get stricter',
    highlights: [
      'Anatomy and Physiology I now has a source-anchored anatomy genome shard, so the linker can cover real A&P lessons instead of calling one weak concept match clean.',
      'Native authoring recovers missing skeleton resources instead of falling back to prose when Pass A names resources but the skeleton omits them.',
      'Required Assets now classifies A&P as an anatomy lab course with models, histology slides, lab manuals, and specimen/model policy; the grader flags geology or chemistry field kits in A&P packages.',
      'Texture is score-bearing: repeated package templates and low texture now create findings, so 100/A cannot hide same-pattern prose.',
      'Ready-state UI is calmer and more truthful: weak knowledge coverage says "Limited knowledge check", material coverage is not confused with learning coverage, duplicate ZIP CTAs are hidden, and dependency tooltips use plainer wording.',
      'Genome builds are reproducible again: anatomy and physics foundry sources validate cleanly and rebuild the shipped shards from explicit source files.',
    ],
  },
  {
    version: '0.15.5',
    date: 'June 14, 2026',
    title: 'The Truth Ledger: the changelog becomes a contract',
    highlights: [
      'Release metadata now has one current source: package version, app version, latest-release popover, top changelog entry, and workspace/config/footer labels all derive from the release manifest.',
      'The changelog keeps v0.15.5 as the generated current entry while preserving v0.15.4 as a historical contract-backed release instead of burying the truthfulness work.',
      'Current release claims now require a machine-readable contract with claim ids, changelog indexes, code/doc anchors, proof commands, and proof-scope labels.',
      'The old v0.15.4 "Moving the Means" roadmap is explicitly marked superseded/carry-forward, with the remaining depth, judge-mean, instructor, and diet lanes moved into future work instead of implied as shipped.',
      'Release-history audit now fails on version drift, missing contracts, stale footer versions, stale default comments, missing roadmap sections, invalid claim metadata, duplicate claim indexes, or anchors that no longer exist.',
      'Remote proof is now named honestly: local proof, fast CI, deep CI, live-provider proof, and manual-human proof are separate contract buckets, so a release cannot imply current deep proof without recording the run.',
    ],
  },
  {
    version: '0.15.4',
    date: 'June 14, 2026',
    title: 'Truthful Course Packages: the audit catches what teachers see',
    highlights: [
      'Linear Algebra no longer inherits the wrong lab identity: "Computational lab in Python" stays computational, while physical supplies still appear for real wet-lab courses with specimens, safety equipment, hand lenses, or field notebooks.',
      'Sparse secondary course-map rows now repair from their own topic before borrowing from sibling sections, so "dimension" does not carry "bases" objectives/resources and review/exam rows stop inheriting stale topic content.',
      'Assessment identity is stricter: problem sets and computational labs about midterm/final review stay graded artifacts instead of becoming full exam records.',
      'Study guides keep topic-specific language after title compression; the pass no longer creates learner-facing phrases like "this lesson criterion" or generic "the lesson" questions.',
      'Math slide decks gain deterministic Linear Algebra worked examples when enrichment is missing, including chartable numeric steps for systems, matrices, determinants, bases, projections, eigenvalues, and SVD.',
      'The package grader now flags physical wet-lab Required Assets in non-wet-lab courses, generic lesson-artifact placeholders, and unevaluated structured-STEM judgments, so these packages cannot quietly claim a perfect 100/A.',
    ],
  },
];
