import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
export default defineConfig({
  plugins: [react()],
  test: {
    setupFiles: ['./tests/setup/unitEnvironment.js'],
    maxWorkers: 2,
    testTimeout: 30000,
    include: [
      'src/contexts/__tests__/AuthContext.test.jsx',
      'src/components/__tests__/{UserMenu,EmailSignInButton}.test.jsx',
      'src/lib/__tests__/accountCacheIsolation.test.js',
      'src/screens/__tests__/CustomDeliverableBuilder.test.jsx',
      'src/components/config/__tests__/InstitutionProfileCard.test.jsx',
      'src/lib/__tests__/codingPracticeReact.test.jsx',
      'src/lib/__tests__/{deliverablePostProcess,packageZipExporter}.test.js',
      'src/lib/__tests__/courseStore.test.js',
      'src/lib/__tests__/explicitLessonSequence.test.js',
      'src/lib/__tests__/practiceCaseExposure.test.js',
      'src/lib/__tests__/propositionalLogicQuiz.test.js',
      'src/lib/quality/__tests__/practiceRecordSubstance.test.js',
      'src/lib/__tests__/packageLessonIdentity.test.js',
      'src/lib/__tests__/requiredLabAssets.test.js',
      'src/lib/quality/__tests__/deepQualityStructure.test.js',
      'src/components/deliverables/__tests__/*.{test,spec}.{js,jsx}',
      'src/components/chat/__tests__/{AgentWorkingSetPanel,AgentQualityControl,MessageList.workspacePlan,ChatPanel.agentCommands}.test.jsx',
      'src/components/__tests__/{GenericDeliverableView,ExportSidePanel.readiness,Header,CourseMapLiveProgress,LessonSourceReview}.test.jsx',
      'src/lib/__tests__/v02006AuditFixes.test.{js,jsx}',
      'src/lib/__tests__/v02007*.test.{js,jsx}',
      'src/lib/__tests__/v02008*.test.{js,jsx}',
      'src/lib/__tests__/v02009*.test.{js,jsx}',
      'src/lib/__tests__/{detectLessons,deliverableSchemas,exporterUtils,generationCancellation,scionCompilerRoute,keyMaps,directExportIntegrity}.test.js',
      'tests/v01654-editable-object-fields.test.jsx',
      'tests/v015-sync-durable.test.jsx',
      'tests/v0147-sync-star.test.js',
      'tests/v0157-finished-package-surface.test.jsx',
      'src/hooks/__tests__/{useDeliverableUndo,useBoundedAutosave,useProjectPersistenceDrafts,useExport}.test.jsx',
      'src/lib/__tests__/{teachingReviewDrafts,projectAutosave,projectSnapshotSanitizer,workspaceSaveStatus}.test.js',
      'src/lib/__tests__/teachingTaskContent*.test.js',
      'src/lib/__tests__/teachingProgram*.test.js',
      'src/lib/__tests__/teachingOperation*.test.js',
      'src/lib/__tests__/teachingPerformanceRequirements.test.js',
      'src/lib/__tests__/teachingArgumentProposal.test.js',
      'src/lib/__tests__/quizPaperPresentation.test.js',
      'src/lib/__tests__/googleStudentExport.test.js',
      'src/lib/__tests__/teachingTaskReview.test.js',
      'src/lib/__tests__/teachingResponseReview.test.js',
      'src/lib/__tests__/teachingTaskCreation.test.js',
      'src/lib/__tests__/teachingGoalAlignment.test.js',
      'src/lib/__tests__/deliverableEditHistory.test.js',
      'src/lib/__tests__/instructionalPlanLineage.test.js',
      'src/lib/courseGraph/__tests__/courseGraph.test.js',
    ],
  },
});
