export const CROSS_PACKAGE_THIN_BRIEF_PANEL_VERSION = '1.0.0';

export const CROSS_PACKAGE_THIN_BRIEFS = [
  {
    id: 'thin-marine-biology',
    courseName: 'Marine Biology Field Methods',
    lessonTitles: [
      'Ocean Systems and Field Questions',
      'Plankton Sampling',
      'Rocky Intertidal Transects',
      'Seagrass Habitat Surveys',
      'Coral Health Indicators',
      'Fish Population Observation',
      'Marine Food Web Evidence',
      'Water Quality Measurements',
      'Human Impacts on Coasts',
      'Conservation Study Design',
      'Field Data Interpretation',
      'Marine Research Briefing',
    ],
  },
  {
    id: 'thin-corporate-tax',
    courseName: 'Corporate Tax Strategy',
    lessonTitles: [
      'Corporate Taxable Income',
      'Property Contributions',
      'Distributions and Earnings',
      'Stock Redemptions',
      'Corporate Reorganizations',
      'Consolidated Returns',
      'Net Operating Losses',
      'International Tax Exposure',
      'Transfer Pricing',
      'Tax Credits and Incentives',
      'Transaction Risk Review',
      'Board Tax Recommendation',
    ],
  },
  {
    id: 'thin-baroque-counterpoint',
    courseName: 'Baroque Counterpoint and Analysis',
    lessonTitles: [
      'Species Counterpoint Review',
      'Two Voice Invention',
      'Imitative Entries',
      'Sequence and Episode',
      'Dissonance Treatment',
      'Invertible Counterpoint',
      'Fugue Subject Design',
      'Exposition Analysis',
      'Stretto and Augmentation',
      'Tonal Answer Decisions',
      'Bach Score Analysis',
      'Original Contrapuntal Study',
    ],
  },
  {
    id: 'thin-epidemiology',
    courseName: 'Applied Epidemiology',
    lessonTitles: [
      'Measures of Disease Frequency',
      'Study Populations',
      'Outbreak Case Definitions',
      'Descriptive Epidemiology',
      'Cohort Study Design',
      'Case Control Study Design',
      'Bias and Confounding',
      'Screening Test Performance',
      'Causal Inference',
      'Surveillance Data',
      'Outbreak Investigation',
      'Public Health Evidence Brief',
    ],
  },
  {
    id: 'thin-civil-procedure',
    courseName: 'Civil Procedure',
    lessonTitles: [
      'Subject Matter Jurisdiction',
      'Personal Jurisdiction',
      'Venue and Transfer',
      'Pleading Standards',
      'Joinder of Claims and Parties',
      'Discovery Scope',
      'Summary Judgment',
      'Trial and Judgment',
      'Claim Preclusion',
      'Issue Preclusion',
      'Class Actions',
      'Litigation Strategy Memorandum',
    ],
  },
  {
    id: 'thin-materials-science',
    courseName: 'Materials Science Laboratory',
    lessonTitles: [
      'Atomic Bonding and Structure',
      'Crystal Lattices',
      'Defects and Diffusion',
      'Phase Diagrams',
      'Mechanical Testing',
      'Fracture and Fatigue',
      'Polymer Behavior',
      'Ceramic Properties',
      'Electronic Materials',
      'Corrosion Analysis',
      'Material Selection',
      'Design Failure Report',
    ],
  },
  {
    id: 'thin-language-pedagogy',
    courseName: 'Second-Language Pedagogy',
    lessonTitles: [
      'Language Acquisition Perspectives',
      'Communicative Competence',
      'Input and Interaction',
      'Vocabulary Instruction',
      'Grammar in Context',
      'Pronunciation Teaching',
      'Listening and Reading',
      'Speaking and Writing',
      'Corrective Feedback',
      'Classroom Task Design',
      'Language Assessment',
      'Teaching Portfolio',
    ],
  },
  {
    id: 'thin-urban-planning',
    courseName: 'Urban Planning Studio',
    lessonTitles: [
      'Planning Problems and Stakeholders',
      'Land Use Analysis',
      'Demographic Evidence',
      'Transportation Networks',
      'Housing Affordability',
      'Public Space Observation',
      'Environmental Justice',
      'Zoning Alternatives',
      'Community Engagement',
      'Scenario Evaluation',
      'Plan Visualization',
      'Public Planning Proposal',
    ],
  },
  {
    id: 'thin-medical-ethics',
    courseName: 'Clinical and Medical Ethics',
    lessonTitles: [
      'Ethical Reasoning in Care',
      'Informed Consent',
      'Decision-Making Capacity',
      'Confidentiality',
      'End-of-Life Decisions',
      'Resource Allocation',
      'Research Ethics',
      'Reproductive Ethics',
      'Pediatric Decision Making',
      'Disability and Care',
      'Ethics Consultation',
      'Clinical Ethics Case Conference',
    ],
  },
  {
    id: 'thin-database-systems',
    courseName: 'Database Systems',
    lessonTitles: [
      'Relational Data Models',
      'Entity Relationship Design',
      'Relational Algebra',
      'SQL Queries',
      'Normalization',
      'Transactions',
      'Concurrency Control',
      'Index Structures',
      'Query Optimization',
      'Distributed Databases',
      'Data Security',
      'Database Design Project',
    ],
  },
  {
    id: 'thin-art-history',
    courseName: 'Modern Art History',
    lessonTitles: [
      'Modernity and Visual Culture',
      'Impressionism',
      'Post-Impressionism',
      'Cubism',
      'Dada and Surrealism',
      'Bauhaus and Design',
      'Abstract Expressionism',
      'Pop Art',
      'Conceptual Art',
      'Feminist Art',
      'Global Contemporary Art',
      'Curatorial Argument',
    ],
  },
  {
    id: 'thin-sports-physiology',
    courseName: 'Exercise and Sports Physiology',
    lessonTitles: [
      'Energy Systems',
      'Neuromuscular Function',
      'Cardiovascular Responses',
      'Respiratory Responses',
      'Endurance Adaptation',
      'Strength Adaptation',
      'Thermoregulation',
      'Hydration and Nutrition',
      'Fatigue and Recovery',
      'Performance Testing',
      'Training Program Design',
      'Athlete Performance Report',
    ],
  },
];

export function buildThinBriefCourseMap(brief) {
  return {
    courseName: brief.courseName,
    semester: 'Fall 2026',
    learningOutcomes: [],
    lessons: brief.lessonTitles.map((title, index) => ({
      title: `Week ${index + 1}: ${title}`,
      sections: [{}],
    })),
  };
}
