export const CROSS_PACKAGE_UNTUNED_BRIEF_PANEL_VERSION = '1.0.0';

export const CROSS_PACKAGE_UNTUNED_BRIEFS = [
  {
    id: 'untuned-museum-registration',
    courseName: 'Museum Registration Workflows',
    lessonTitles: [
      'Object Intake Records',
      'Accession Numbering',
      'Condition Note Routing',
      'Location Control',
      'Loan File Assembly',
      'Courier Arrangements',
      'Insurance Documentation',
      'Inventory Reconciliation',
    ],
  },
  {
    id: 'untuned-hospitality-front-desk',
    courseName: 'Hospitality Front Desk Operations',
    lessonTitles: [
      'Reservation Handoffs',
      'Arrival Preparation',
      'Guest Check In',
      'Room Status Coordination',
      'Service Request Routing',
      'Shift Reconciliation',
      'Departure Processing',
      'Night Audit Handoff',
    ],
  },
  {
    id: 'untuned-apparel-merchandising',
    courseName: 'Apparel Merchandising Practice',
    lessonTitles: [
      'Assortment Vocabulary',
      'Seasonal Line Review',
      'Size Curve Planning',
      'Vendor Sample Tracking',
      'Floor Set Coordination',
      'Markdown Scheduling',
      'Sell Through Review',
      'Assortment Recommendation',
    ],
  },
  {
    id: 'untuned-event-venue-operations',
    courseName: 'Event Venue Operations',
    lessonTitles: [
      'Venue Walkthrough',
      'Room Set Documentation',
      'Vendor Arrival Windows',
      'Equipment Handoffs',
      'Guest Flow Monitoring',
      'Changeover Coordination',
      'Closing Checklist',
      'Operations Debrief',
    ],
  },
  {
    id: 'untuned-library-preservation',
    courseName: 'Library Collections Preservation',
    lessonTitles: [
      'Handling Survey',
      'Storage Environment',
      'Housing Selection',
      'Surface Cleaning',
      'Damage Documentation',
      'Vendor Preparation',
      'Emergency Priorities',
      'Preservation Workplan',
    ],
  },
  {
    id: 'untuned-construction-coordination',
    courseName: 'Construction Site Coordination',
    lessonTitles: [
      'Daily Site Log',
      'Trade Sequencing',
      'Material Delivery Windows',
      'Access Route Coordination',
      'Inspection Readiness',
      'Open Item Tracking',
      'Turnover Documentation',
      'Coordination Meeting',
    ],
  },
  {
    id: 'untuned-aviation-ground-services',
    courseName: 'Aviation Ground Services',
    lessonTitles: [
      'Stand Preparation',
      'Arrival Handoff',
      'Baggage Flow',
      'Cabin Service Sequence',
      'Load Document Routing',
      'Pushback Coordination',
      'Delay Communication',
      'Turnaround Review',
    ],
  },
  {
    id: 'untuned-retail-category-management',
    courseName: 'Retail Category Management',
    lessonTitles: [
      'Category Role',
      'Shelf Review',
      'Item Performance',
      'Promotion Calendar',
      'Vendor Meeting',
      'Space Allocation',
      'Reset Preparation',
      'Category Recommendation',
    ],
  },
  {
    id: 'untuned-funeral-service-operations',
    courseName: 'Funeral Service Operations',
    lessonTitles: [
      'Arrangement File',
      'Transfer Coordination',
      'Service Order',
      'Facility Preparation',
      'Family Communication Log',
      'Merchandise Record',
      'Disposition Documents',
      'Case Closeout',
    ],
  },
  {
    id: 'untuned-parks-maintenance',
    courseName: 'Parks Maintenance Supervision',
    lessonTitles: [
      'Work Order Review',
      'Crew Assignment',
      'Equipment Readiness',
      'Grounds Inspection',
      'Facility Checklist',
      'Supply Tracking',
      'Seasonal Handoff',
      'Maintenance Briefing',
    ],
  },
  {
    id: 'untuned-beverage-operations',
    courseName: 'Craft Beverage Operations',
    lessonTitles: [
      'Production Log',
      'Ingredient Receiving',
      'Vessel Preparation',
      'Batch Handoff',
      'Packaging Schedule',
      'Inventory Count',
      'Taproom Coordination',
      'Operations Review',
    ],
  },
  {
    id: 'untuned-records-management',
    courseName: 'Organizational Records Management',
    lessonTitles: [
      'Record Inventory',
      'File Plan',
      'Retention Schedule',
      'Disposition Hold',
      'Inactive Storage',
      'Access Request Routing',
      'Transfer Documentation',
      'Program Review',
    ],
  },
];

export function buildUntunedBriefCourseMap(brief) {
  return {
    courseName: brief.courseName,
    semester: 'Fall 2026',
    learningOutcomes: [],
    lessons: brief.lessonTitles.map((title, index) => ({
      title: `Week ${index + 1}: ${title}`,
      sections: [{}],
    })),
  };
}
