export const EXTENDED_REAL_COURSE_DEFINITIONS = [
  {
    name: 'library archives practicum',
    courseName: 'Library Archives Practicum',
    lessonCount: 8,
    theme: 'archives stewardship',
    lens: 'collection appraisal, metadata, preservation risk, and access decisions',
    artifact: 'archive processing note',
    evidence: 'collection records, provenance notes, metadata gaps, and preservation constraints',
    asyncTask: 'Review a finding-aid excerpt and identify one metadata gap',
    syncTask: 'Processing lab with appraisal discussion and description revision',
    resource: 'finding-aid model; metadata worksheet; preservation checklist',
    evaluation: 'Score provenance evidence, description accuracy, access reasoning, and revision',
    featureIds: ['lessonPlans', 'assignments', 'studyGuides', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'translation studies workshop',
    courseName: 'Translation Studies Workshop',
    lessonCount: 8,
    theme: 'translation practice',
    lens: 'source-text analysis, audience, register, ethics, and revision',
    artifact: 'translation commentary',
    evidence: 'source-text features, lexical decisions, audience constraints, and revision notes',
    asyncTask: 'Translate a short passage and mark one register decision',
    syncTask: 'Translation workshop with peer comparison and commentary revision',
    resource: 'source passage; glossary; translation commentary model',
    evaluation: 'Score source fidelity, audience fit, decision rationale, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'geographic information systems lab',
    courseName: 'Geographic Information Systems Lab',
    lessonCount: 14,
    theme: 'spatial analysis',
    lens: 'geodata provenance, map design, spatial joins, and uncertainty',
    artifact: 'GIS analysis map brief',
    evidence: 'layer metadata, projection choices, spatial query results, and uncertainty notes',
    asyncTask: 'Inspect a map layer and identify one data-quality issue',
    syncTask: 'GIS lab with spatial join practice and map critique',
    resource: 'sample layers; map design checklist; metadata guide',
    evaluation: 'Score data provenance, spatial reasoning, cartographic clarity, and limitation language',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
    exportFeatureIds: ['syllabus', 'lessonPlans', 'assignments'],
  },
  {
    name: 'robotics controls lab',
    courseName: 'Robotics Controls Lab',
    lessonCount: 14,
    theme: 'robotics control',
    lens: 'sensor evidence, control loops, testing, and failure analysis',
    artifact: 'robotics test report',
    evidence: 'sensor logs, controller settings, failure traces, and redesign notes',
    asyncTask: 'Review a robot log and predict one control issue',
    syncTask: 'Controls lab with test run, log interpretation, and iteration',
    resource: 'sensor log sample; controller checklist; test report template',
    evaluation: 'Score control reasoning, test evidence, failure diagnosis, and redesign plan',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'public speaking intensive',
    courseName: 'Public Speaking Intensive',
    lessonCount: 3,
    theme: 'oral communication',
    lens: 'audience analysis, evidence, delivery, and feedback uptake',
    artifact: 'speech revision plan',
    evidence: 'audience notes, speech recording evidence, peer feedback, and delivery choices',
    asyncTask: 'Watch a speech clip and mark one audience adaptation',
    syncTask: 'Speech rehearsal with peer feedback and revised delivery',
    resource: 'speech model; delivery checklist; feedback form',
    evaluation: 'Score audience fit, evidence, delivery choice, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'labor relations negotiation seminar',
    courseName: 'Labor Relations Negotiation Seminar',
    lessonCount: 8,
    theme: 'negotiation practice',
    lens: 'interests, legal context, bargaining evidence, and agreement drafting',
    artifact: 'negotiation strategy memo',
    evidence: 'case facts, stakeholder interests, legal constraints, and concession logic',
    asyncTask: 'Review a negotiation case and identify one hidden interest',
    syncTask: 'Role-play negotiation with caucus notes and debrief',
    resource: 'case packet; bargaining map; strategy memo template',
    evaluation: 'Score interest analysis, evidence, legal boundary, and strategy revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'veterinary case reasoning',
    courseName: 'Veterinary Case Reasoning',
    lessonCount: 8,
    theme: 'veterinary reasoning',
    lens: 'case history, diagnostics, welfare, communication, and clinical boundaries',
    artifact: 'veterinary case note',
    evidence: 'case-history cues, diagnostic options, welfare considerations, and client communication notes',
    asyncTask: 'Review a de-identified case and mark one diagnostic question',
    syncTask: 'Case round with evidence sorting and client communication rehearsal',
    resource: 'de-identified case packet; diagnostic checklist; communication guide',
    evaluation: 'Score evidence use, diagnostic reasoning, welfare considerations, and communication clarity',
    caution: 'Flag clinical safety requirements and local veterinary policy for human review.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_clinicalPolicyBinder'],
    customFeatureIds: ['custom_clinicalPolicyBinder'],
  },
  {
    name: 'occupational therapy documentation',
    courseName: 'Occupational Therapy Documentation',
    lessonCount: 8,
    theme: 'therapy documentation',
    lens: 'client goals, functional evidence, intervention planning, and documentation boundaries',
    artifact: 'therapy progress note',
    evidence: 'functional observations, client goals, intervention evidence, and referral cues',
    asyncTask: 'Review a de-identified note and identify one evidence gap',
    syncTask: 'Documentation lab with peer calibration and revision',
    resource: 'de-identified case; documentation checklist; scope boundary note',
    evaluation: 'Score functional evidence, goal alignment, clarity, and scope boundary awareness',
    caution: 'Use de-identified practice material and confirm local clinical documentation policy.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'dental hygiene patient education',
    courseName: 'Dental Hygiene Patient Education',
    lessonCount: 8,
    theme: 'patient education',
    lens: 'oral health evidence, communication, behavior change, and safety boundaries',
    artifact: 'patient education script',
    evidence: 'case cues, risk factors, plain-language explanation, and teach-back notes',
    asyncTask: 'Review a de-identified case and draft one teach-back question',
    syncTask: 'Patient-education role-play with feedback and revision',
    resource: 'de-identified case; teach-back guide; plain-language checklist',
    evaluation: 'Score evidence accuracy, communication clarity, teach-back use, and boundary awareness',
    caution: 'Confirm clinical safety and local policy before classroom use.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'biostatistics consultation practicum',
    courseName: 'Biostatistics Consultation Practicum',
    lessonCount: 8,
    theme: 'statistical consulting',
    lens: 'client question, study design, analysis choice, and communication',
    artifact: 'consultation memo',
    evidence: 'client question, variable definitions, model assumptions, and limitation language',
    asyncTask: 'Review a client question and identify one design constraint',
    syncTask: 'Consulting clinic with assumption check and memo revision',
    resource: 'client brief; model-choice checklist; memo example',
    evaluation: 'Score question fit, analysis reasoning, assumption transparency, and client communication',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'energy policy modeling',
    courseName: 'Energy Policy Modeling',
    lessonCount: 14,
    theme: 'energy policy',
    lens: 'model assumptions, emissions evidence, costs, equity, and policy tradeoffs',
    artifact: 'energy policy model memo',
    evidence: 'model inputs, emissions scenarios, cost assumptions, and equity implications',
    asyncTask: 'Inspect a scenario table and mark one assumption risk',
    syncTask: 'Policy modeling lab with scenario comparison and memo revision',
    resource: 'scenario table; model assumption guide; policy memo template',
    evaluation: 'Score assumption transparency, evidence, tradeoff reasoning, and recommendation',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'quizBank', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
    exportFeatureIds: ['syllabus', 'lessonPlans', 'assignments'],
  },
  {
    name: 'climate adaptation planning',
    courseName: 'Climate Adaptation Planning Studio',
    lessonCount: 8,
    theme: 'adaptation planning',
    lens: 'hazard evidence, vulnerability, stakeholder priorities, and implementation',
    artifact: 'adaptation action brief',
    evidence: 'hazard maps, vulnerability indicators, stakeholder needs, and feasibility constraints',
    asyncTask: 'Review a hazard map and mark one vulnerable asset',
    syncTask: 'Planning studio with adaptation option comparison and critique',
    resource: 'hazard map; vulnerability table; action brief model',
    evaluation: 'Score hazard evidence, vulnerability reasoning, feasibility, and equity',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'international relations crisis simulation',
    courseName: 'International Relations Crisis Simulation',
    lessonCount: 3,
    theme: 'crisis diplomacy',
    lens: 'actor interests, intelligence evidence, negotiation, and escalation risk',
    artifact: 'crisis decision memo',
    evidence: 'actor positions, intelligence notes, alliance constraints, and escalation tradeoffs',
    asyncTask: 'Read a crisis brief and identify one uncertainty',
    syncTask: 'Simulation round with decision logging and debrief',
    resource: 'crisis packet; actor map; decision log',
    evaluation: 'Score actor analysis, evidence, tradeoff reasoning, and debrief revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'philosophy thought experiment seminar',
    courseName: 'Philosophy Thought Experiment Seminar',
    lessonCount: 8,
    theme: 'philosophical reasoning',
    lens: 'conceptual distinctions, thought experiments, objections, and replies',
    artifact: 'argument reconstruction',
    evidence: 'passage claims, conceptual distinctions, examples, and objection responses',
    asyncTask: 'Read a short argument and identify one hidden premise',
    syncTask: 'Seminar with argument mapping and objection workshop',
    resource: 'argument passage; concept map; reconstruction rubric',
    evaluation: 'Score reconstruction accuracy, objection strength, reply quality, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_readingResponse'],
    customFeatureIds: ['custom_readingResponse'],
  },
  {
    name: 'anthropology fieldnotes workshop',
    courseName: 'Anthropology Fieldnotes Workshop',
    lessonCount: 8,
    theme: 'ethnographic observation',
    lens: 'fieldnotes, reflexivity, coding, ethics, and interpretation',
    artifact: 'fieldnote analytic memo',
    evidence: 'observation notes, positionality reflections, codes, and interpretive limits',
    asyncTask: 'Read a fieldnote excerpt and mark one reflexivity issue',
    syncTask: 'Fieldnotes workshop with coding comparison and memo revision',
    resource: 'fieldnote excerpt; coding guide; ethics checklist',
    evaluation: 'Score observation specificity, reflexivity, coding evidence, and interpretation limits',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'sociology survey design',
    courseName: 'Sociology Survey Design Lab',
    lessonCount: 8,
    theme: 'survey research',
    lens: 'constructs, question wording, sampling, and validity evidence',
    artifact: 'survey design memo',
    evidence: 'construct definitions, item wording, sampling plan, and pilot feedback',
    asyncTask: 'Review survey items and identify one validity threat',
    syncTask: 'Survey lab with cognitive interview notes and item revision',
    resource: 'survey draft; cognitive interview guide; validity checklist',
    evaluation: 'Score construct fit, wording quality, sampling logic, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'behavioral economics experiment lab',
    courseName: 'Behavioral Economics Experiment Lab',
    lessonCount: 8,
    theme: 'behavioral economics',
    lens: 'incentives, experimental design, bias, and interpretation',
    artifact: 'behavioral experiment memo',
    evidence: 'treatment design, outcome measures, bias checks, and interpretation limits',
    asyncTask: 'Review an experiment design and mark one confound',
    syncTask: 'Experiment lab with design critique and interpretation revision',
    resource: 'experiment brief; bias checklist; memo model',
    evaluation: 'Score design logic, evidence, bias reasoning, and policy interpretation',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'financial risk management cases',
    courseName: 'Financial Risk Management Cases',
    lessonCount: 8,
    theme: 'risk management',
    lens: 'market risk, credit risk, controls, stress testing, and communication',
    artifact: 'risk case brief',
    evidence: 'risk metrics, scenario assumptions, control evidence, and decision limits',
    asyncTask: 'Review a risk table and identify one exposure',
    syncTask: 'Case lab with stress-test comparison and recommendation',
    resource: 'risk table; stress-test worksheet; case brief model',
    evaluation: 'Score metric interpretation, scenario reasoning, controls, and recommendation clarity',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'tax policy clinic',
    courseName: 'Tax Policy Clinic',
    lessonCount: 8,
    theme: 'tax policy',
    lens: 'statutory rules, incidence evidence, equity, and administrative feasibility',
    artifact: 'tax policy brief',
    evidence: 'statutory excerpts, revenue estimates, incidence analysis, and implementation constraints',
    asyncTask: 'Review a tax proposal and identify one distributional claim',
    syncTask: 'Policy clinic with incidence mapping and brief revision',
    resource: 'statutory excerpt; incidence table; policy brief template',
    evaluation: 'Score statutory accuracy, evidence, equity analysis, and feasibility',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'real estate development feasibility',
    courseName: 'Real Estate Development Feasibility',
    lessonCount: 8,
    theme: 'development feasibility',
    lens: 'site analysis, financial assumptions, stakeholder constraints, and risk',
    artifact: 'feasibility memo',
    evidence: 'site data, pro forma assumptions, zoning constraints, and market risks',
    asyncTask: 'Review a pro forma excerpt and mark one assumption risk',
    syncTask: 'Feasibility lab with site critique and memo revision',
    resource: 'site packet; pro forma model; zoning checklist',
    evaluation: 'Score site evidence, financial logic, constraint reasoning, and risk communication',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  },
  {
    name: 'hospitality operations practicum',
    courseName: 'Hospitality Operations Practicum',
    lessonCount: 8,
    theme: 'hospitality operations',
    lens: 'guest evidence, service standards, operations metrics, and recovery',
    artifact: 'service recovery plan',
    evidence: 'guest feedback, operations metrics, service standards, and recovery options',
    asyncTask: 'Review a guest complaint and identify one service gap',
    syncTask: 'Operations practicum with role-play and recovery plan critique',
    resource: 'guest feedback packet; service standard; recovery checklist',
    evaluation: 'Score guest evidence, operations logic, communication, and improvement plan',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'sports analytics scouting lab',
    courseName: 'Sports Analytics Scouting Lab',
    lessonCount: 8,
    theme: 'sports analytics',
    lens: 'performance data, film evidence, context, and scouting recommendation',
    artifact: 'scouting analytics brief',
    evidence: 'performance metrics, film notes, context adjustments, and recommendation limits',
    asyncTask: 'Review a stat line and mark one context caveat',
    syncTask: 'Scouting lab with film-note comparison and brief revision',
    resource: 'performance table; film-note guide; scouting brief model',
    evaluation: 'Score metric interpretation, context reasoning, evidence synthesis, and recommendation',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'game design playtest studio',
    courseName: 'Game Design Playtest Studio',
    lessonCount: 8,
    theme: 'game design',
    lens: 'mechanics, player evidence, balancing, and iteration',
    artifact: 'playtest report',
    evidence: 'player observations, balance metrics, rule changes, and design rationale',
    asyncTask: 'Playtest a small mechanic and record one player behavior',
    syncTask: 'Studio playtest with observation coding and redesign critique',
    resource: 'playtest protocol; mechanics worksheet; iteration log',
    evaluation: 'Score observation evidence, design rationale, balance reasoning, and iteration',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'animation storyboarding studio',
    courseName: 'Animation Storyboarding Studio',
    lessonCount: 8,
    theme: 'storyboarding',
    lens: 'visual sequence, timing, critique, and revision',
    artifact: 'storyboard revision packet',
    evidence: 'thumbnail sequences, timing notes, critique comments, and revised panels',
    asyncTask: 'Annotate a storyboard sequence and mark one timing issue',
    syncTask: 'Studio critique with sequence review and panel revision',
    resource: 'storyboard sample; timing checklist; critique form',
    evaluation: 'Score sequence clarity, visual evidence, critique uptake, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'film studies scene analysis',
    courseName: 'Film Studies Scene Analysis',
    lessonCount: 8,
    theme: 'film analysis',
    lens: 'shot evidence, sound, editing, context, and argument',
    artifact: 'scene analysis memo',
    evidence: 'shot notes, sound cues, editing patterns, and interpretive claims',
    asyncTask: 'Watch a scene and mark one formal choice',
    syncTask: 'Scene seminar with evidence comparison and argument revision',
    resource: 'scene clip; shot-list model; analysis rubric',
    evaluation: 'Score formal evidence, context, interpretive claim, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_readingResponse'],
    customFeatureIds: ['custom_readingResponse'],
  },
  {
    name: 'visual arts critique seminar',
    courseName: 'Visual Arts Critique Seminar',
    lessonCount: 8,
    theme: 'visual arts critique',
    lens: 'formal evidence, artist intent, peer critique, and revision',
    artifact: 'critique reflection',
    evidence: 'work-in-progress images, formal analysis, peer notes, and revision decisions',
    asyncTask: 'Prepare a critique note naming one formal choice',
    syncTask: 'Critique circle with evidence-based peer feedback and revision planning',
    resource: 'critique protocol; formal analysis guide; reflection template',
    evaluation: 'Score specificity, evidence, critique uptake, and revision plan',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_selfAssessment'],
    customFeatureIds: ['custom_selfAssessment'],
  },
  {
    name: 'dance composition workshop',
    courseName: 'Dance Composition Workshop',
    lessonCount: 8,
    theme: 'dance composition',
    lens: 'movement motif, spatial design, rehearsal evidence, and critique',
    artifact: 'movement revision log',
    evidence: 'rehearsal video notes, motif choices, spatial decisions, and critique uptake',
    asyncTask: 'Watch rehearsal footage and mark one movement choice',
    syncTask: 'Movement workshop with peer observation and revised phrase',
    resource: 'movement score; rehearsal log; critique checklist',
    evaluation: 'Score movement evidence, spatial intention, critique uptake, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_selfAssessment'],
    customFeatureIds: ['custom_selfAssessment'],
  },
  {
    name: 'theater production management',
    courseName: 'Theater Production Management',
    lessonCount: 8,
    theme: 'production management',
    lens: 'schedule, budget, safety, team communication, and risk',
    artifact: 'production checkpoint report',
    evidence: 'production calendar, budget notes, safety constraints, and team updates',
    asyncTask: 'Review a production calendar and identify one risk',
    syncTask: 'Production meeting simulation with checkpoint review and revision',
    resource: 'production calendar; budget sheet; safety checklist',
    evaluation: 'Score planning evidence, risk reasoning, communication, and revision',
    caution: 'Confirm local venue safety requirements before publishing production guidance.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  },
  {
    name: 'nutrition counseling lab',
    courseName: 'Nutrition Counseling Lab',
    lessonCount: 8,
    theme: 'nutrition counseling',
    lens: 'dietary evidence, client goals, counseling communication, and scope boundaries',
    artifact: 'nutrition counseling plan',
    evidence: 'diet recall notes, client goals, behavior-change evidence, and referral cues',
    asyncTask: 'Review a de-identified diet recall and mark one counseling question',
    syncTask: 'Counseling role-play with feedback and revised plan',
    resource: 'de-identified recall; counseling guide; scope boundary note',
    evaluation: 'Score evidence use, goal alignment, communication, and referral boundary',
    caution: 'Confirm clinical nutrition policy and scope requirements before use.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'kinesiology movement assessment',
    courseName: 'Kinesiology Movement Assessment',
    lessonCount: 8,
    theme: 'movement assessment',
    lens: 'movement observation, biomechanics evidence, feedback, and safety',
    artifact: 'movement assessment note',
    evidence: 'video observations, joint-action notes, cueing decisions, and safety considerations',
    asyncTask: 'Watch a movement clip and mark one biomechanical cue',
    syncTask: 'Assessment lab with observation comparison and cueing practice',
    resource: 'movement clip; observation checklist; safety note',
    evaluation: 'Score observation accuracy, biomechanical reasoning, feedback cue, and safety',
    caution: 'Flag local safety and scope requirements for human review.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'radiology image interpretation seminar',
    courseName: 'Radiology Image Interpretation Seminar',
    lessonCount: 8,
    theme: 'image interpretation',
    lens: 'visual evidence, differential reasoning, communication, and clinical review boundaries',
    artifact: 'image interpretation note',
    evidence: 'image observations, differential cues, uncertainty, and communication notes',
    asyncTask: 'Review a de-identified image description and mark one observation',
    syncTask: 'Image seminar with observation comparison and uncertainty debrief',
    resource: 'de-identified image packet; observation guide; local review reminder',
    evaluation: 'Score visual evidence, reasoning, uncertainty language, and communication',
    caution: 'Use teaching-only de-identified examples and require clinical expert review.',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_clinicalPolicyBinder'],
    customFeatureIds: ['custom_clinicalPolicyBinder'],
  },
  {
    name: 'medical ethics case conference',
    courseName: 'Medical Ethics Case Conference',
    lessonCount: 8,
    theme: 'medical ethics',
    lens: 'case facts, principles, patient values, policy boundaries, and recommendation',
    artifact: 'ethics consultation memo',
    evidence: 'case facts, stakeholder values, policy constraints, and principle conflicts',
    asyncTask: 'Review a de-identified case and identify one ethical tension',
    syncTask: 'Case conference with principle mapping and memo revision',
    resource: 'de-identified case; principles guide; local policy review note',
    evaluation: 'Score fact use, principle reasoning, stakeholder sensitivity, and policy boundary',
    caution: 'Confirm institution policy and clinical ethics requirements before classroom use.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'education data privacy workshop',
    courseName: 'Education Data Privacy Workshop',
    lessonCount: 3,
    theme: 'education data privacy',
    lens: 'student data, consent, platform risk, institution policy, and classroom practice',
    artifact: 'privacy review checklist',
    evidence: 'data-flow notes, policy excerpts, platform risks, and classroom constraints',
    asyncTask: 'Review a platform scenario and identify one data risk',
    syncTask: 'Privacy workshop with scenario triage and checklist revision',
    resource: 'data-flow model; privacy checklist; policy review note',
    evaluation: 'Score data-flow evidence, risk reasoning, policy boundary, and classroom action',
    caution: 'Confirm institution policy and legal requirements before publishing.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'accessibility design clinic',
    courseName: 'Accessibility Design Clinic',
    lessonCount: 8,
    theme: 'accessibility design',
    lens: 'user needs, standards evidence, testing, and remediation',
    artifact: 'accessibility remediation plan',
    evidence: 'user needs, accessibility checks, test results, and remediation rationale',
    asyncTask: 'Inspect a page or document and mark one accessibility barrier',
    syncTask: 'Clinic with assistive-technology check and remediation critique',
    resource: 'accessibility checklist; sample artifact; remediation template',
    evaluation: 'Score barrier evidence, standard fit, testing, and remediation clarity',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'assistive technology evaluation',
    courseName: 'Assistive Technology Evaluation',
    lessonCount: 8,
    theme: 'assistive technology',
    lens: 'learner need, device evidence, usability, ethics, and implementation',
    artifact: 'assistive technology evaluation brief',
    evidence: 'learner scenarios, device observations, usability notes, and implementation constraints',
    asyncTask: 'Review a device scenario and identify one usability question',
    syncTask: 'Evaluation lab with observation comparison and recommendation revision',
    resource: 'device scenario; usability checklist; recommendation template',
    evaluation: 'Score learner fit, evidence, usability reasoning, and implementation plan',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'instructional design storyboard',
    courseName: 'Instructional Design Storyboard',
    lessonCount: 8,
    theme: 'instructional design',
    lens: 'learning goals, activity alignment, media decisions, and evaluation',
    artifact: 'learning module storyboard',
    evidence: 'objective alignment, media choices, practice activities, and evaluation evidence',
    asyncTask: 'Review a module sample and identify one alignment gap',
    syncTask: 'Storyboard studio with peer review and module revision',
    resource: 'storyboard template; alignment checklist; media guide',
    evaluation: 'Score objective alignment, practice fit, media rationale, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  },
  {
    name: 'community organizing campaign lab',
    courseName: 'Community Organizing Campaign Lab',
    lessonCount: 8,
    theme: 'community organizing',
    lens: 'power analysis, stakeholder evidence, campaign tactics, and reflection',
    artifact: 'campaign action brief',
    evidence: 'stakeholder map, listening notes, tactic rationale, and reflection evidence',
    asyncTask: 'Review a campaign case and mark one power relationship',
    syncTask: 'Campaign lab with strategy critique and action plan revision',
    resource: 'campaign case; power map; action brief template',
    evaluation: 'Score stakeholder evidence, tactic fit, ethical reflection, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'conflict mediation skills',
    courseName: 'Conflict Mediation Skills',
    lessonCount: 8,
    theme: 'mediation practice',
    lens: 'party interests, reframing, process ethics, and agreement options',
    artifact: 'mediation process note',
    evidence: 'role-play transcript, interests, reframing attempts, and agreement options',
    asyncTask: 'Review a conflict scenario and identify one underlying interest',
    syncTask: 'Mediation role-play with observation coding and debrief',
    resource: 'role-play scenario; observation checklist; ethics guide',
    evaluation: 'Score interest analysis, communication skill, process ethics, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'leadership decision cases',
    courseName: 'Leadership Decision Cases',
    lessonCount: 8,
    theme: 'leadership decision making',
    lens: 'context evidence, team dynamics, values, and decision communication',
    artifact: 'leadership case memo',
    evidence: 'case facts, team signals, value conflicts, and decision consequences',
    asyncTask: 'Read a leadership case and identify one decision pressure',
    syncTask: 'Case discussion with decision mapping and memo revision',
    resource: 'case packet; decision map; leadership memo model',
    evaluation: 'Score context evidence, value reasoning, team awareness, and communication',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'organizational change consulting',
    courseName: 'Organizational Change Consulting',
    lessonCount: 8,
    theme: 'organizational change',
    lens: 'stakeholder diagnosis, change readiness, intervention design, and feedback',
    artifact: 'change consulting brief',
    evidence: 'stakeholder interviews, readiness indicators, intervention options, and feedback evidence',
    asyncTask: 'Review a change case and identify one resistance signal',
    syncTask: 'Consulting lab with diagnosis critique and brief revision',
    resource: 'change case; readiness checklist; consulting brief template',
    evaluation: 'Score diagnosis, evidence, intervention fit, and feedback uptake',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'operations research modeling',
    courseName: 'Operations Research Modeling',
    lessonCount: 14,
    theme: 'optimization modeling',
    lens: 'decision variables, constraints, objective functions, sensitivity, and communication',
    artifact: 'optimization model memo',
    evidence: 'model formulation, solver output, sensitivity results, and limitation notes',
    asyncTask: 'Review a formulation and identify one missing constraint',
    syncTask: 'Modeling lab with solver interpretation and memo revision',
    resource: 'formulation worksheet; solver output; sensitivity checklist',
    evaluation: 'Score formulation accuracy, constraint logic, interpretation, and recommendation',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  },
  {
    name: 'database administration recovery lab',
    courseName: 'Database Administration Recovery Lab',
    lessonCount: 8,
    theme: 'database administration',
    lens: 'backup evidence, incident logs, recovery objectives, and risk communication',
    artifact: 'recovery runbook checkpoint',
    evidence: 'backup logs, recovery objectives, incident timeline, and validation checks',
    asyncTask: 'Review a backup log and identify one recovery risk',
    syncTask: 'Recovery lab with runbook testing and postmortem debrief',
    resource: 'backup log; runbook template; validation checklist',
    evaluation: 'Score evidence, recovery logic, validation, and communication',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  },
  {
    name: 'cloud architecture design review',
    courseName: 'Cloud Architecture Design Review',
    lessonCount: 8,
    theme: 'cloud architecture',
    lens: 'requirements, reliability, security, cost, and tradeoff documentation',
    artifact: 'architecture decision record',
    evidence: 'requirements, service limits, cost assumptions, and risk tradeoffs',
    asyncTask: 'Review an architecture diagram and mark one reliability risk',
    syncTask: 'Design review with tradeoff analysis and decision-record revision',
    resource: 'architecture diagram; decision-record template; cost checklist',
    evaluation: 'Score requirement fit, reliability, security, cost reasoning, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'information security governance',
    courseName: 'Information Security Governance',
    lessonCount: 8,
    theme: 'security governance',
    lens: 'risk register, controls, policy boundaries, and executive communication',
    artifact: 'security governance memo',
    evidence: 'risk entries, control evidence, policy constraints, and residual risk notes',
    asyncTask: 'Review a risk register and identify one control gap',
    syncTask: 'Governance case lab with control mapping and memo revision',
    resource: 'risk register; control framework excerpt; memo template',
    evaluation: 'Score risk evidence, control logic, policy boundary, and communication',
    caution: 'Confirm local security policy before publishing operational guidance.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'digital forensics evidence lab',
    courseName: 'Digital Forensics Evidence Lab',
    lessonCount: 8,
    theme: 'digital forensics',
    lens: 'evidence handling, chain of custody, analysis logs, and reporting',
    artifact: 'forensics evidence report',
    evidence: 'image metadata, analysis logs, chain-of-custody notes, and report limits',
    asyncTask: 'Review a sanitized evidence log and mark one custody issue',
    syncTask: 'Forensics lab with evidence handling simulation and report revision',
    resource: 'sanitized evidence log; chain-of-custody checklist; report model',
    evaluation: 'Score evidence handling, analysis trace, report clarity, and boundary awareness',
    caution: 'Use sanitized teaching evidence and confirm legal or institutional policy.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'astronomy observation lab',
    courseName: 'Astronomy Observation Lab',
    lessonCount: 8,
    theme: 'astronomical observation',
    lens: 'observation planning, measurement, uncertainty, and interpretation',
    artifact: 'observation report',
    evidence: 'observation logs, instrument settings, measurement uncertainty, and sky-condition notes',
    asyncTask: 'Review an observation log and identify one uncertainty source',
    syncTask: 'Observation lab with data comparison and report revision',
    resource: 'observation log; instrument guide; report template',
    evaluation: 'Score observation planning, measurement evidence, uncertainty, and interpretation',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'geology field mapping',
    courseName: 'Geology Field Mapping',
    lessonCount: 8,
    theme: 'geology fieldwork',
    lens: 'site observation, stratigraphic evidence, map symbols, and interpretation',
    artifact: 'field mapping report',
    evidence: 'outcrop notes, stratigraphic sketches, map annotations, and uncertainty limits',
    asyncTask: 'Review a field sketch and mark one interpretive question',
    syncTask: 'Field mapping lab with observation comparison and map revision',
    resource: 'field sketch; map legend; safety checklist',
    evaluation: 'Score observation evidence, mapping accuracy, interpretation, and safety boundary',
    caution: 'Confirm local field safety requirements before use.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'oceanography data lab',
    courseName: 'Oceanography Data Lab',
    lessonCount: 8,
    theme: 'oceanographic data',
    lens: 'sensor data, environmental context, visualization, and uncertainty',
    artifact: 'ocean data analysis brief',
    evidence: 'sensor readings, visualization choices, context notes, and uncertainty language',
    asyncTask: 'Inspect a sensor table and identify one quality issue',
    syncTask: 'Data lab with visualization critique and brief revision',
    resource: 'sensor table; visualization checklist; analysis brief model',
    evaluation: 'Score data quality, visualization reasoning, context, and interpretation limits',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'materials science testing',
    courseName: 'Materials Science Testing Lab',
    lessonCount: 8,
    theme: 'materials testing',
    lens: 'test setup, stress-strain evidence, failure modes, and design recommendation',
    artifact: 'materials test report',
    evidence: 'test data, stress-strain plots, failure observations, and material-selection rationale',
    asyncTask: 'Review a stress-strain plot and mark one failure cue',
    syncTask: 'Testing lab with data comparison and recommendation critique',
    resource: 'test data; plot guide; report template',
    evaluation: 'Score test evidence, failure analysis, material reasoning, and recommendation',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'construction management safety',
    courseName: 'Construction Management Safety',
    lessonCount: 8,
    theme: 'construction management',
    lens: 'site constraints, schedule, safety, cost, and stakeholder coordination',
    artifact: 'construction safety checkpoint',
    evidence: 'site plans, schedule risks, safety observations, and coordination notes',
    asyncTask: 'Review a site plan and identify one safety constraint',
    syncTask: 'Safety planning lab with risk review and checkpoint revision',
    resource: 'site plan; safety checklist; schedule excerpt',
    evaluation: 'Score site evidence, safety reasoning, schedule risk, and coordination plan',
    caution: 'Confirm local site safety and regulatory requirements before publishing.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  },
  {
    name: 'civil engineering water systems',
    courseName: 'Civil Engineering Water Systems',
    lessonCount: 14,
    theme: 'water systems engineering',
    lens: 'hydraulic evidence, design constraints, public safety, and resilience',
    artifact: 'water systems design memo',
    evidence: 'flow calculations, infrastructure constraints, resilience assumptions, and safety factors',
    asyncTask: 'Review a flow table and identify one design constraint',
    syncTask: 'Design lab with calculation check and memo revision',
    resource: 'flow table; design criteria; resilience checklist',
    evaluation: 'Score calculation evidence, design fit, safety reasoning, and resilience tradeoffs',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  },
  {
    name: 'aerospace mission design',
    courseName: 'Aerospace Mission Design Studio',
    lessonCount: 14,
    theme: 'mission design',
    lens: 'requirements, trajectory evidence, mass budget, risk, and design review',
    artifact: 'mission design review memo',
    evidence: 'mission requirements, trajectory assumptions, mass budget, and risk register',
    asyncTask: 'Review a mission brief and mark one requirement risk',
    syncTask: 'Design review with tradeoff analysis and memo revision',
    resource: 'mission brief; mass budget sheet; risk register',
    evaluation: 'Score requirement trace, calculation evidence, risk reasoning, and design recommendation',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'quizBank', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
    exportFeatureIds: ['syllabus', 'lessonPlans', 'assignments'],
  },
  {
    name: 'manufacturing process improvement',
    courseName: 'Manufacturing Process Improvement',
    lessonCount: 8,
    theme: 'manufacturing improvement',
    lens: 'process evidence, variation, constraints, and continuous improvement',
    artifact: 'process improvement report',
    evidence: 'process maps, defect data, variation signals, and improvement rationale',
    asyncTask: 'Review a process map and identify one bottleneck',
    syncTask: 'Improvement lab with root-cause analysis and report revision',
    resource: 'process map; defect table; root-cause checklist',
    evaluation: 'Score process evidence, variation reasoning, feasibility, and improvement plan',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'quality assurance audit practicum',
    courseName: 'Quality Assurance Audit Practicum',
    lessonCount: 8,
    theme: 'quality assurance',
    lens: 'audit evidence, standards, corrective action, and verification',
    artifact: 'audit finding report',
    evidence: 'audit observations, standard references, root cause, and corrective-action evidence',
    asyncTask: 'Review an audit observation and classify one finding',
    syncTask: 'Audit lab with evidence calibration and corrective-action planning',
    resource: 'audit sample; standards excerpt; corrective-action template',
    evaluation: 'Score evidence, standard fit, root-cause reasoning, and verification plan',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'sustainable agriculture field lab',
    courseName: 'Sustainable Agriculture Field Lab',
    lessonCount: 8,
    theme: 'agriculture field evidence',
    lens: 'soil evidence, crop observations, sustainability tradeoffs, and local constraints',
    artifact: 'field management note',
    evidence: 'soil tests, crop observations, management practices, and sustainability indicators',
    asyncTask: 'Review a soil test and identify one management question',
    syncTask: 'Field lab with observation comparison and management-note revision',
    resource: 'soil test; field observation protocol; sustainability checklist',
    evaluation: 'Score field evidence, sustainability reasoning, feasibility, and revision',
    caution: 'Confirm local field safety requirements before use.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'food safety inspection lab',
    courseName: 'Food Safety Inspection Lab',
    lessonCount: 8,
    theme: 'food safety',
    lens: 'hazard evidence, inspection protocol, corrective action, and regulation boundary',
    artifact: 'inspection checklist report',
    evidence: 'hazard observations, temperature logs, sanitation notes, and corrective actions',
    asyncTask: 'Review an inspection scenario and mark one hazard',
    syncTask: 'Inspection lab with observation calibration and report revision',
    resource: 'inspection scenario; HACCP checklist; corrective-action guide',
    evaluation: 'Score hazard evidence, protocol use, corrective action, and boundary awareness',
    caution: 'Confirm local food safety regulation and policy before publishing.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'wildlife conservation planning',
    courseName: 'Wildlife Conservation Planning',
    lessonCount: 8,
    theme: 'conservation planning',
    lens: 'habitat evidence, population data, stakeholder constraints, and management tradeoffs',
    artifact: 'conservation action brief',
    evidence: 'habitat maps, population indicators, stakeholder priorities, and management risks',
    asyncTask: 'Review a habitat map and mark one management constraint',
    syncTask: 'Planning lab with evidence comparison and action-brief revision',
    resource: 'habitat map; population table; action brief template',
    evaluation: 'Score ecological evidence, stakeholder reasoning, feasibility, and recommendation',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'marine policy negotiation',
    courseName: 'Marine Policy Negotiation',
    lessonCount: 3,
    theme: 'marine policy',
    lens: 'resource evidence, stakeholder interests, legal constraints, and negotiation',
    artifact: 'marine policy agreement brief',
    evidence: 'resource data, stakeholder positions, legal constraints, and tradeoff options',
    asyncTask: 'Review a fisheries case and identify one stakeholder conflict',
    syncTask: 'Negotiation simulation with agreement drafting and debrief',
    resource: 'fisheries case; stakeholder map; agreement template',
    evaluation: 'Score resource evidence, legal boundary, tradeoff reasoning, and agreement clarity',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'religious studies textual analysis',
    courseName: 'Religious Studies Textual Analysis',
    lessonCount: 8,
    theme: 'textual analysis',
    lens: 'passage evidence, historical context, interpretive traditions, and respectful discourse',
    artifact: 'textual analysis response',
    evidence: 'passage details, context notes, interpretive claims, and comparison evidence',
    asyncTask: 'Annotate a passage and identify one interpretive question',
    syncTask: 'Seminar with respectful comparison and response revision',
    resource: 'passage packet; context guide; discussion protocol',
    evaluation: 'Score textual evidence, context, comparison, and respectful reasoning',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_readingResponse'],
    customFeatureIds: ['custom_readingResponse'],
  },
  {
    name: 'linguistics phonetics lab',
    courseName: 'Linguistics Phonetics Lab',
    lessonCount: 8,
    theme: 'phonetics analysis',
    lens: 'sound evidence, transcription, acoustic cues, and interpretation',
    artifact: 'phonetics lab report',
    evidence: 'audio observations, IPA transcription, acoustic measurements, and interpretation limits',
    asyncTask: 'Listen to an audio sample and mark one phonetic cue',
    syncTask: 'Phonetics lab with transcription comparison and report revision',
    resource: 'audio sample; IPA chart; acoustic analysis guide',
    evaluation: 'Score transcription accuracy, evidence, interpretation, and correction',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  },
  {
    name: 'creative nonfiction workshop',
    courseName: 'Creative Nonfiction Workshop',
    lessonCount: 8,
    theme: 'creative nonfiction',
    lens: 'scene evidence, voice, ethical representation, and revision',
    artifact: 'nonfiction revision packet',
    evidence: 'draft excerpts, research notes, peer comments, and revision rationale',
    asyncTask: 'Annotate a draft scene and identify one craft move',
    syncTask: 'Workshop with craft feedback and revision planning',
    resource: 'model essay; peer response guide; revision checklist',
    evaluation: 'Score craft evidence, ethical representation, feedback uptake, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  },
  {
    name: 'poetry forms studio',
    courseName: 'Poetry Forms Studio',
    lessonCount: 8,
    theme: 'poetry craft',
    lens: 'form, sound, image, critique, and revision',
    artifact: 'poetry revision portfolio',
    evidence: 'draft poems, form notes, peer critique, and revision rationale',
    asyncTask: 'Annotate a poem and mark one formal choice',
    syncTask: 'Poetry workshop with form critique and revision planning',
    resource: 'poem packet; form guide; critique protocol',
    evaluation: 'Score craft intentionality, evidence, critique uptake, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_selfAssessment'],
    customFeatureIds: ['custom_selfAssessment'],
  },
  {
    name: 'digital humanities annotation lab',
    courseName: 'Digital Humanities Annotation Lab',
    lessonCount: 8,
    theme: 'digital humanities',
    lens: 'text encoding, metadata, interpretive evidence, and tool limits',
    artifact: 'annotation project checkpoint',
    evidence: 'encoded passages, metadata choices, interpretive notes, and tool limitations',
    asyncTask: 'Annotate a digital text and mark one encoding decision',
    syncTask: 'Annotation lab with schema comparison and checkpoint revision',
    resource: 'digital text; encoding guide; metadata worksheet',
    evaluation: 'Score encoding evidence, metadata logic, interpretation, and limitation language',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  },
  {
    name: 'educational measurement seminar',
    courseName: 'Educational Measurement Seminar',
    lessonCount: 8,
    theme: 'measurement validity',
    lens: 'construct definition, evidence, reliability, fairness, and score use',
    artifact: 'validity evidence memo',
    evidence: 'construct claims, item evidence, reliability data, and fairness concerns',
    asyncTask: 'Review an assessment sample and identify one validity claim',
    syncTask: 'Measurement seminar with evidence mapping and memo revision',
    resource: 'assessment sample; validity framework; evidence map template',
    evaluation: 'Score construct clarity, evidence quality, fairness reasoning, and score-use caution',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'student affairs advising practice',
    courseName: 'Student Affairs Advising Practice',
    lessonCount: 8,
    theme: 'advising practice',
    lens: 'student scenario evidence, policy boundaries, referral, and communication',
    artifact: 'advising case note',
    evidence: 'student scenario cues, policy constraints, referral options, and communication notes',
    asyncTask: 'Review a de-identified advising scenario and mark one referral cue',
    syncTask: 'Advising role-play with observation feedback and case-note revision',
    resource: 'de-identified scenario; referral guide; policy review note',
    evaluation: 'Score evidence, policy boundary, referral reasoning, and communication',
    caution: 'Confirm institution policy and student support protocol before use.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  },
  {
    name: 'college success coaching',
    courseName: 'College Success Coaching',
    lessonCount: 8,
    theme: 'success coaching',
    lens: 'student goals, barriers, resource navigation, and reflective planning',
    artifact: 'success coaching plan',
    evidence: 'student goal notes, barrier analysis, campus resources, and action steps',
    asyncTask: 'Review a student scenario and identify one support resource',
    syncTask: 'Coaching role-play with feedback and action-plan revision',
    resource: 'student scenario; resource map; action-plan template',
    evaluation: 'Score goal fit, evidence, support navigation, and action specificity',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_selfAssessment'],
    customFeatureIds: ['custom_selfAssessment'],
  },
  {
    name: 'public administration budgeting',
    courseName: 'Public Administration Budgeting',
    lessonCount: 8,
    theme: 'public budgeting',
    lens: 'budget evidence, program priorities, equity, and accountability',
    artifact: 'budget decision memo',
    evidence: 'budget tables, program goals, equity indicators, and accountability measures',
    asyncTask: 'Review a budget table and identify one tradeoff',
    syncTask: 'Budget lab with priority mapping and memo revision',
    resource: 'budget table; program brief; decision memo model',
    evaluation: 'Score fiscal evidence, program fit, equity reasoning, and accountability',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  },
  {
    name: 'legal writing motion practice',
    courseName: 'Legal Writing Motion Practice',
    lessonCount: 8,
    theme: 'legal writing',
    lens: 'procedural posture, rule application, record evidence, and revision',
    artifact: 'motion argument draft',
    evidence: 'record excerpts, rule statements, case comparisons, and counterarguments',
    asyncTask: 'Read a record excerpt and identify one legally relevant fact',
    syncTask: 'Writing workshop with argument mapping and draft revision',
    resource: 'record excerpt; motion sample; citation checklist',
    evaluation: 'Score rule accuracy, record evidence, argument structure, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
  {
    name: 'forensic psychology case seminar',
    courseName: 'Forensic Psychology Case Seminar',
    lessonCount: 8,
    theme: 'forensic psychology',
    lens: 'case evidence, assessment limits, legal context, and ethics',
    artifact: 'forensic case analysis',
    evidence: 'case facts, assessment cues, legal standards, and ethical limits',
    asyncTask: 'Review a de-identified case and identify one assessment limit',
    syncTask: 'Case seminar with evidence sorting and analysis revision',
    resource: 'de-identified case; ethics checklist; legal context note',
    evaluation: 'Score evidence, assessment limit language, legal context, and ethics',
    caution: 'Use de-identified teaching cases and confirm legal or clinical policy.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  },
];
