import { scenario } from './blueprintQualityScenarioFactory.js';

export const CORE_REAL_COURSE_SCENARIOS = [
  scenario({
    name: 'single lesson seminar source analysis',
    courseName: 'Rapid Source Analysis Seminar',
    lessonCount: 1,
    theme: 'source analysis',
    lens: 'seminar argument and evidence triangulation',
    artifact: 'source analysis memo',
    evidence: 'primary-source claims, citation gaps, and competing interpretations',
    asyncTask: 'Read two short source excerpts and mark claims that need corroboration',
    syncTask: 'Seminar discussion with claim-evidence mapping',
    resource: 'primary-source packet; citation guide',
    evaluation: 'Use the memo rubric to check claim, evidence, limitation, and revision quality',
    topics: ['Claim, Context, and Corroboration'],
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'rubrics', 'courseFaq'],
  }),
  scenario({
    name: 'three lesson policy memo studio',
    courseName: 'Policy Memo Studio',
    lessonCount: 3,
    theme: 'policy analysis',
    lens: 'public decision making and implementation risk',
    artifact: 'policy memo checkpoint',
    evidence: 'stakeholder evidence, feasibility constraints, and equity tradeoffs',
    asyncTask: 'Review a policy case packet and extract stakeholder evidence',
    syncTask: 'Policy lab with tradeoff mapping and memo peer review',
    resource: 'case packet; stakeholder map; memo model',
    evaluation: 'Score recommendation logic, source use, feasibility, and equity reasoning',
    topics: ['Problem Framing', 'Alternatives and Evidence', 'Recommendation and Revision'],
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'courseFaq', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  }),
  scenario({
    name: 'biology lab methods',
    courseName: 'Biology Laboratory Methods',
    lessonCount: 8,
    theme: 'wet-lab method',
    lens: 'measurement, protocol control, and lab safety',
    artifact: 'lab report shell',
    evidence: 'replicate data, uncertainty notes, contamination evidence, and protocol deviations',
    asyncTask: 'Review protocol videos and mark safety or measurement decisions',
    syncTask: 'Wet-lab practice with replicate checks and troubleshooting debrief',
    resource: 'protocol guide; lab safety checklist; data table template',
    evaluation: 'Score technique, data integrity, safety reasoning, and protocol revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  }),
  scenario({
    name: 'large data science lab',
    courseName: 'Applied Data Science Lab',
    lessonCount: 14,
    theme: 'data science',
    lens: 'notebook workflow, model validation, and fairness review',
    artifact: 'analysis notebook checkpoint',
    evidence: 'dataset provenance, validation metrics, error analysis, and model-card limits',
    asyncTask: 'Inspect a data dictionary and reproduce one notebook cell',
    syncTask: 'Lab sprint with pair debugging, metric interpretation, and model-card critique',
    resource: 'sample notebook; data dictionary; model-card template',
    evaluation: 'Score reproducibility, metric reasoning, bias check, and communication clarity',
    featureIds: ['syllabus', 'lessonPlans', 'slideDecks', 'quizBank', 'studyGuides'],
    exportFeatureIds: ['syllabus', 'lessonPlans', 'studyGuides'],
  }),
  scenario({
    name: 'performing arts studio',
    courseName: 'Acting Studio and Performance Practice',
    lessonCount: 8,
    theme: 'performance rehearsal',
    lens: 'voice, movement, ensemble cues, and critique uptake',
    artifact: 'rehearsal journal entry',
    evidence: 'performance recording notes, director feedback, and revised choices',
    asyncTask: 'Annotate a scene excerpt and mark one performance choice',
    syncTask: 'Studio rehearsal with peer observation and second run-through',
    resource: 'scene packet; rehearsal journal; vocal safety guide',
    evaluation: 'Score technique, evidence, note uptake, and observable revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_selfAssessment'],
    customFeatureIds: ['custom_selfAssessment'],
  }),
  scenario({
    name: 'online writing workshop',
    courseName: 'Online Writing Workshop',
    lessonCount: 8,
    theme: 'writing revision',
    lens: 'audience, genre, feedback, and portfolio reflection',
    artifact: 'revision plan',
    evidence: 'draft excerpts, peer comments, genre conventions, and revision rationale',
    asyncTask: 'Annotate a model draft and identify one revision move',
    syncTask: 'Remote workshop with response roles and revision planning',
    resource: 'draft model; peer response guide; accessibility note',
    evaluation: 'Score genre fit, feedback uptake, evidence, and revision specificity',
    featureIds: ['syllabus', 'lessonPlans', 'discussions', 'studyGuides', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'business case method',
    courseName: 'Business Case Method',
    lessonCount: 8,
    theme: 'case method decision making',
    lens: 'market evidence, operations constraints, and executive communication',
    artifact: 'case brief',
    evidence: 'case facts, financial signals, stakeholder constraints, and decision risks',
    asyncTask: 'Read the case and prepare a one-page decision note',
    syncTask: 'Cold-call case discussion with board-plan synthesis',
    resource: 'case packet; decision tree; executive memo sample',
    evaluation: 'Score diagnosis, evidence selection, decision tradeoffs, and recommendation clarity',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'courseFaq', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  }),
  scenario({
    name: 'world language proficiency',
    courseName: 'Beginning Spanish Communicative Practice',
    lessonCount: 8,
    theme: 'language proficiency',
    lens: 'interpersonal, interpretive, and presentational communication',
    artifact: 'target-language performance script',
    evidence: 'vocabulary use, pronunciation notes, grammar patterns, and cultural comparison',
    asyncTask: 'Listen to model audio and mark comprehensibility cues',
    syncTask: 'Conversation stations with recasts and performance revision',
    resource: 'audio models; phrase bank; cultural formality guide',
    evaluation: 'Score comprehensibility, accuracy, cultural fit, and feedback-based revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'studyGuides'],
  }),
  scenario({
    name: 'constitutional law doctrine',
    courseName: 'Constitutional Law Doctrine',
    lessonCount: 8,
    theme: 'legal doctrine',
    lens: 'case holding, rule synthesis, and constitutional argument',
    artifact: 'case rule memo',
    evidence: 'holdings, doctrinal tests, dissents, and policy implications',
    asyncTask: 'Brief assigned cases and identify the governing rule',
    syncTask: 'Socratic case comparison with rule-application drills',
    resource: 'case packet; doctrine map; argument checklist',
    evaluation: 'Score rule accuracy, case evidence, counterargument, and application quality',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'rubrics'],
  }),
  scenario({
    name: 'clinical caution counseling practice',
    courseName: 'Counseling Skills Practice',
    lessonCount: 8,
    theme: 'helping-skills practice',
    lens: 'role-play, observation coding, ethics, and referral boundaries',
    artifact: 'practice case note',
    evidence: 'transcript excerpts, observation codes, risk cues, and supervision feedback',
    asyncTask: 'Review de-identified role-play clips and mark listening skills',
    syncTask: 'Supervised role-play with observation coding and ethics debrief',
    resource: 'de-identified scenario packet; ethics checklist; referral boundary note',
    evaluation: 'Score skill evidence, ethics reasoning, supervision uptake, and no-clinical-advice boundaries',
    caution: 'Use de-identified practice scenarios only and flag local clinical policy for review.',
    featureIds: [
      'syllabus',
      'lessonPlans',
      'discussions',
      'custom_observationChecklist',
      'custom_clinicalPolicyBinder',
    ],
    customFeatureIds: ['custom_observationChecklist', 'custom_clinicalPolicyBinder'],
  }),
  scenario({
    name: 'engineering design lab',
    courseName: 'Engineering Design Lab',
    lessonCount: 8,
    theme: 'engineering design',
    lens: 'requirements, prototype testing, constraints, and iteration',
    artifact: 'prototype test report',
    evidence: 'requirement traces, test data, failure modes, and design rationale',
    asyncTask: 'Inspect a requirements brief and predict a test risk',
    syncTask: 'Prototype lab with test logging and design review',
    resource: 'requirements sheet; test log; design-review rubric',
    evaluation: 'Score requirement alignment, test evidence, failure analysis, and iteration plan',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'courseFaq', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  }),
  scenario({
    name: 'quantitative problem set',
    courseName: 'Quantitative Methods Problem Set',
    lessonCount: 8,
    theme: 'quantitative reasoning',
    lens: 'problem setup, assumptions, computation, and interpretation',
    artifact: 'problem set worksheet',
    evidence: 'formula selection, calculation traces, assumption checks, and error analysis',
    asyncTask: 'Complete diagnostic practice and mark uncertain steps',
    syncTask: 'Problem-solving studio with worked-example comparison',
    resource: 'formula sheet; worked examples; error-analysis checklist',
    evaluation: 'Score setup, computation, interpretation, and error correction',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  }),
  scenario({
    name: 'statistics inference seminar',
    courseName: 'Statistical Inference for Social Research',
    lessonCount: 8,
    theme: 'statistical inference',
    lens: 'sampling, uncertainty, estimation, and validity',
    artifact: 'inference memo',
    evidence: 'sampling frame, confidence interval, p-value interpretation, and validity limits',
    asyncTask: 'Interpret a small study result and identify an uncertainty claim',
    syncTask: 'Inference clinic with misconception checks and peer explanation',
    resource: 'study abstract; inference checklist; simulation applet',
    evaluation: 'Score interpretation, assumption reasoning, uncertainty language, and validity limits',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'studyGuides'],
  }),
  scenario({
    name: 'accounting finance analysis',
    courseName: 'Accounting and Financial Statement Analysis',
    lessonCount: 8,
    theme: 'financial analysis',
    lens: 'statements, ratios, cash flow, and audit questions',
    artifact: 'financial analysis brief',
    evidence: 'statement excerpts, ratio calculations, trend evidence, and risk notes',
    asyncTask: 'Review a financial statement excerpt and calculate one ratio',
    syncTask: 'Analysis workshop with peer check and risk discussion',
    resource: 'statement packet; ratio guide; audit question checklist',
    evaluation: 'Score calculation accuracy, interpretation, evidence use, and risk communication',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank'],
  }),
  scenario({
    name: 'ethics argument seminar',
    courseName: 'Ethics and Technology Argument Seminar',
    lessonCount: 8,
    theme: 'ethical argument',
    lens: 'stakeholder values, principles, harms, and justified action',
    artifact: 'ethical argument brief',
    evidence: 'stakeholder claims, principle conflicts, harm evidence, and counterargument',
    asyncTask: 'Read a dilemma packet and identify competing principles',
    syncTask: 'Structured debate with evidence checks and revision',
    resource: 'dilemma cases; principle guide; argument rubric',
    evaluation: 'Score principle use, evidence, counterargument, and action recommendation',
    featureIds: ['syllabus', 'lessonPlans', 'discussions', 'rubrics'],
  }),
  scenario({
    name: 'proof seminar',
    courseName: 'Introduction to Mathematical Proof',
    lessonCount: 8,
    theme: 'proof reasoning',
    lens: 'definitions, claims, counterexamples, and proof structure',
    artifact: 'proof portfolio entry',
    evidence: 'definition use, example testing, proof steps, and error diagnosis',
    asyncTask: 'Attempt a short proof and annotate the stuck point',
    syncTask: 'Proof workshop with counterexample search and board critique',
    resource: 'definition sheet; proof model; common-error guide',
    evaluation: 'Score logical structure, definition use, counterexample handling, and revision',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'studyGuides', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  }),
  scenario({
    name: 'lecture exam review course',
    courseName: 'Foundations Lecture and Exam Review',
    lessonCount: 14,
    theme: 'concept review',
    lens: 'lecture synthesis, retrieval practice, and exam transfer',
    artifact: 'exam review guide',
    evidence: 'concept definitions, misconception checks, practice item rationales, and transfer prompts',
    asyncTask: 'Watch a lecture clip and complete retrieval practice',
    syncTask: 'Review session with misconception polling and transfer problem discussion',
    resource: 'lecture notes; practice bank; review checklist',
    evaluation: 'Score concept accuracy, rationale quality, misconception repair, and transfer readiness',
    featureIds: ['syllabus', 'lessonPlans', 'slideDecks', 'quizBank', 'studyGuides'],
    exportFeatureIds: ['syllabus', 'lessonPlans', 'quizBank'],
  }),
  scenario({
    name: 'capstone project progress',
    courseName: 'Capstone Project Studio',
    lessonCount: 14,
    theme: 'capstone development',
    lens: 'proposal, evidence, prototype, feedback, and final defense',
    artifact: 'capstone progress report',
    evidence: 'project milestones, advisor feedback, prototype evidence, and scope decisions',
    asyncTask: 'Update the project log and identify one decision needing feedback',
    syncTask: 'Studio critique with milestone review and revision planning',
    resource: 'proposal template; progress tracker; critique protocol',
    evaluation: 'Score milestone evidence, scope control, feedback uptake, and next-step clarity',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'courseFaq', 'custom_capstoneProgress'],
    customFeatureIds: ['custom_capstoneProgress'],
  }),
  scenario({
    name: 'teacher preparation observation',
    courseName: 'Teacher Preparation Observation Lab',
    lessonCount: 8,
    theme: 'teaching observation',
    lens: 'classroom evidence, instructional moves, and reflective improvement',
    artifact: 'observation checklist',
    evidence: 'student talk, teacher prompts, formative evidence, and reflection notes',
    asyncTask: 'Watch a classroom clip and code two instructional moves',
    syncTask: 'Observation lab with calibration and lesson-revision discussion',
    resource: 'video clip; observation protocol; lesson plan sample',
    evaluation: 'Score observation accuracy, evidence use, reflection, and instructional revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  }),
  scenario({
    name: 'information literacy research course',
    courseName: 'Information Literacy Research Lab',
    lessonCount: 8,
    theme: 'information literacy',
    lens: 'search strategy, source evaluation, synthesis, and citation',
    artifact: 'research log',
    evidence: 'database searches, source credibility, synthesis notes, and citation gaps',
    asyncTask: 'Run a database search and document one search revision',
    syncTask: 'Research clinic with source triage and synthesis mapping',
    resource: 'database guide; source evaluation checklist; citation model',
    evaluation: 'Score search strategy, source quality, synthesis, and citation integrity',
    featureIds: ['lessonPlans', 'assignments', 'studyGuides', 'courseFaq'],
  }),
  scenario({
    name: 'public health policy practice',
    courseName: 'Public Health Policy Practice',
    lessonCount: 8,
    theme: 'public health policy',
    lens: 'population evidence, intervention design, equity, and communication',
    artifact: 'policy intervention brief',
    evidence: 'epidemiology signals, community needs, intervention evidence, and implementation constraints',
    asyncTask: 'Review a public health data snapshot and mark equity questions',
    syncTask: 'Policy design lab with stakeholder map and peer critique',
    resource: 'data snapshot; intervention evidence sheet; equity checklist',
    evaluation: 'Score evidence fit, intervention logic, equity reasoning, and communication clarity',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  }),
  scenario({
    name: 'environmental justice field course',
    courseName: 'Environmental Justice Field Methods',
    lessonCount: 8,
    theme: 'field methods',
    lens: 'site observation, community evidence, risk communication, and ethics',
    artifact: 'field observation note',
    evidence: 'site observations, community testimony, environmental measures, and positionality notes',
    asyncTask: 'Prepare a field protocol and mark one ethics consideration',
    syncTask: 'Field debrief with observation comparison and risk communication practice',
    resource: 'field protocol; consent reminder; observation template',
    evaluation: 'Score observation specificity, ethics, evidence triangulation, and communication',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  }),
  scenario({
    name: 'nursing simulation caution',
    courseName: 'Nursing Simulation Reasoning',
    lessonCount: 8,
    theme: 'simulation reasoning',
    lens: 'patient-safety scenario, prioritization, communication, and debrief',
    artifact: 'simulation reasoning note',
    evidence: 'vital-sign trends, SBAR communication, safety checks, and debrief evidence',
    asyncTask: 'Review a de-identified simulation chart and identify one safety cue',
    syncTask: 'Simulation debrief with prioritization and communication rehearsal',
    resource: 'de-identified simulation chart; SBAR template; local policy review reminder',
    evaluation: 'Score prioritization, evidence use, safety communication, and scope boundary awareness',
    caution: 'Flag clinical safety requirements and local institution policy for human review.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm', 'custom_clinicalPolicyBinder'],
    customFeatureIds: ['custom_feedbackForm', 'custom_clinicalPolicyBinder'],
  }),
  scenario({
    name: 'social work case notes',
    courseName: 'Social Work Case Documentation',
    lessonCount: 8,
    theme: 'case documentation',
    lens: 'de-identified case evidence, strengths, needs, referrals, and ethics',
    artifact: 'case documentation note',
    evidence: 'client scenario details, strengths evidence, referral options, and ethics cues',
    asyncTask: 'Review a de-identified case vignette and mark documentation boundaries',
    syncTask: 'Case-note workshop with evidence calibration and referral discussion',
    resource: 'de-identified vignette; documentation guide; ethics reminder',
    evaluation: 'Score evidence specificity, strengths framing, referral logic, and confidentiality boundary',
    caution: 'Use de-identified examples and flag local agency policy for review.',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'ux research studio',
    courseName: 'UX Research Studio',
    lessonCount: 8,
    theme: 'user research',
    lens: 'interviews, usability evidence, synthesis, and design recommendation',
    artifact: 'research insight brief',
    evidence: 'interview notes, usability observations, affinity themes, and recommendation evidence',
    asyncTask: 'Review interview excerpts and tag one usability issue',
    syncTask: 'Synthesis studio with affinity mapping and recommendation critique',
    resource: 'interview excerpt pack; usability checklist; insight brief model',
    evaluation: 'Score evidence trace, synthesis quality, recommendation fit, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  }),
  scenario({
    name: 'ai literacy seminar',
    courseName: 'AI Literacy for Educators',
    lessonCount: 8,
    theme: 'AI literacy',
    lens: 'tool affordances, classroom use, bias, privacy, and assessment design',
    artifact: 'AI use plan',
    evidence: 'tool behavior notes, privacy risks, bias examples, and classroom constraints',
    asyncTask: 'Test a low-risk AI prompt and note observed limits',
    syncTask: 'Seminar critique with classroom scenario planning and policy review',
    resource: 'tool observation template; privacy checklist; AI policy review note',
    evaluation: 'Score tool evidence, privacy reasoning, bias awareness, and classroom fit',
    featureIds: ['syllabus', 'lessonPlans', 'discussions', 'courseFaq'],
  }),
  scenario({
    name: 'cybersecurity lab',
    courseName: 'Cybersecurity Defensive Lab',
    lessonCount: 8,
    theme: 'defensive cybersecurity',
    lens: 'threat modeling, logs, controls, and incident response',
    artifact: 'defense lab report',
    evidence: 'log excerpts, threat model assumptions, control evidence, and response timeline',
    asyncTask: 'Inspect a sanitized log sample and mark one suspicious pattern',
    syncTask: 'Defensive lab with control testing and incident-response debrief',
    resource: 'sanitized log packet; threat model template; response checklist',
    evaluation: 'Score evidence handling, control reasoning, response clarity, and ethics boundary',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  }),
  scenario({
    name: 'history archive seminar',
    courseName: 'Archival History Seminar',
    lessonCount: 8,
    theme: 'historical interpretation',
    lens: 'archive evidence, context, historiography, and source limits',
    artifact: 'archive analysis memo',
    evidence: 'archival fragments, context notes, historiographic claims, and source silences',
    asyncTask: 'Transcribe a short archival excerpt and mark context questions',
    syncTask: 'Archive seminar with source comparison and interpretation critique',
    resource: 'archive packet; context timeline; citation model',
    evaluation: 'Score context, evidence interpretation, source limits, and argument revision',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'discussions'],
  }),
  scenario({
    name: 'entrepreneurship pitch studio',
    courseName: 'Entrepreneurship Pitch Studio',
    lessonCount: 8,
    theme: 'venture design',
    lens: 'customer discovery, value proposition, evidence, and pitch revision',
    artifact: 'pitch milestone checklist',
    evidence: 'interview evidence, market assumptions, prototype feedback, and financial signals',
    asyncTask: 'Interview one target user and summarize evidence ethically',
    syncTask: 'Pitch studio with peer critique and milestone planning',
    resource: 'interview guide; pitch canvas; milestone checklist',
    evaluation: 'Score customer evidence, value clarity, assumption testing, and revision',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  }),
  scenario({
    name: 'database systems lab',
    courseName: 'Database Systems Lab',
    lessonCount: 14,
    theme: 'database systems',
    lens: 'schema design, query reasoning, transactions, and performance',
    artifact: 'database lab worksheet',
    evidence: 'schema diagrams, query traces, transaction anomalies, and performance observations',
    asyncTask: 'Review a schema and predict one query behavior',
    syncTask: 'SQL lab with query debugging and peer explanation',
    resource: 'schema packet; SQL sandbox; query trace checklist',
    evaluation: 'Score schema reasoning, query correctness, anomaly explanation, and performance interpretation',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'studyGuides', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  }),
  scenario({
    name: 'software engineering code review lab',
    courseName: 'Software Engineering Code Review Lab',
    lessonCount: 14,
    theme: 'software engineering',
    lens: 'requirements, tests, code review, refactoring, and release evidence',
    artifact: 'code review checkpoint',
    evidence: 'test output, code diffs, issue traces, edge cases, and review comments',
    asyncTask: 'Inspect a pull-request diff and identify one test gap',
    syncTask: 'Code review lab with pair debugging and refactor planning',
    resource: 'sample repository; review checklist; test report model',
    evaluation: 'Score correctness, test evidence, readability, edge-case handling, and review uptake',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  }),
  scenario({
    name: 'chemistry safety lab',
    courseName: 'Chemistry Lab Safety and Analysis',
    lessonCount: 8,
    theme: 'chemistry lab',
    lens: 'safety protocol, observation, reaction evidence, and disposal decisions',
    artifact: 'chemistry lab report',
    evidence: 'observation notes, reaction data, safety checks, and uncertainty limits',
    asyncTask: 'Review the safety data sheet and predict one protocol risk',
    syncTask: 'Guided wet-lab with safety check, observation log, and debrief',
    resource: 'safety data sheet; reaction protocol; observation table',
    evaluation: 'Score safety reasoning, data integrity, conclusion limits, and protocol revision',
    caution: 'Confirm local lab safety requirements before classroom use.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_labReport'],
    customFeatureIds: ['custom_labReport'],
  }),
  scenario({
    name: 'physics mechanics problem studio',
    courseName: 'Physics Mechanics Problem Studio',
    lessonCount: 8,
    theme: 'mechanics reasoning',
    lens: 'free-body diagrams, assumptions, equations, and interpretation',
    artifact: 'mechanics problem worksheet',
    evidence: 'diagram choices, equation setup, unit checks, and error analysis',
    asyncTask: 'Attempt a diagnostic problem and mark one assumption',
    syncTask: 'Problem studio with board work, peer explanation, and correction',
    resource: 'formula sheet; worked example; unit-check guide',
    evaluation: 'Score representation, setup, calculation, interpretation, and correction',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  }),
  scenario({
    name: 'urban planning charrette',
    courseName: 'Urban Planning Charrette',
    lessonCount: 8,
    theme: 'urban planning',
    lens: 'site evidence, stakeholder needs, zoning constraints, and design tradeoffs',
    artifact: 'planning concept memo',
    evidence: 'site observations, zoning excerpts, community feedback, and feasibility constraints',
    asyncTask: 'Review a site packet and mark one stakeholder tension',
    syncTask: 'Charrette with site mapping, critique, and concept revision',
    resource: 'site packet; zoning excerpt; stakeholder map',
    evaluation: 'Score site evidence, feasibility, equity, tradeoff reasoning, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  }),
  scenario({
    name: 'architecture studio critique',
    courseName: 'Architecture Studio Critique',
    lessonCount: 8,
    theme: 'architecture design',
    lens: 'precedent analysis, spatial evidence, critique, and iteration',
    artifact: 'design critique board',
    evidence: 'precedent notes, sketches, site constraints, and critique decisions',
    asyncTask: 'Annotate a precedent and identify one spatial strategy',
    syncTask: 'Studio critique with pin-up review and iteration planning',
    resource: 'precedent packet; critique protocol; board template',
    evaluation: 'Score design intent, evidence, critique uptake, and iteration clarity',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'music theory ear training',
    courseName: 'Music Theory and Ear Training',
    lessonCount: 8,
    theme: 'music theory',
    lens: 'aural recognition, notation, harmonic function, and performance transfer',
    artifact: 'ear-training practice log',
    evidence: 'listening notes, notation attempts, harmonic analysis, and feedback corrections',
    asyncTask: 'Listen to a short excerpt and mark interval or chord evidence',
    syncTask: 'Ear-training lab with call-and-response and correction',
    resource: 'audio excerpt; notation guide; harmonic function chart',
    evaluation: 'Score recognition accuracy, notation, explanation, and corrected practice',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_selfAssessment'],
    customFeatureIds: ['custom_selfAssessment'],
  }),
  scenario({
    name: 'journalism reporting lab',
    courseName: 'Journalism Reporting Lab',
    lessonCount: 8,
    theme: 'reporting practice',
    lens: 'source verification, interviewing, story structure, and ethics',
    artifact: 'reported story draft',
    evidence: 'interview notes, verification trail, attribution, and revision rationale',
    asyncTask: 'Review a source packet and identify one verification gap',
    syncTask: 'Reporting lab with interview simulation and editor feedback',
    resource: 'source checklist; attribution guide; story model',
    evaluation: 'Score verification, attribution, story focus, ethics, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'emergency management tabletop',
    courseName: 'Emergency Management Tabletop',
    lessonCount: 3,
    theme: 'emergency management',
    lens: 'incident command, risk communication, resource constraints, and after-action review',
    artifact: 'tabletop action memo',
    evidence: 'scenario injects, decision log, communication choices, and resource tradeoffs',
    asyncTask: 'Review an incident brief and mark one resource constraint',
    syncTask: 'Tabletop exercise with decision logging and after-action debrief',
    resource: 'incident brief; decision log; after-action template',
    evaluation: 'Score prioritization, communication, resource logic, and after-action revision',
    caution: 'Confirm local emergency policy and safety requirements before publishing.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  }),
  scenario({
    name: 'grant writing workshop',
    courseName: 'Grant Writing Workshop',
    lessonCount: 8,
    theme: 'grant writing',
    lens: 'needs evidence, theory of change, budget logic, and reviewer feedback',
    artifact: 'grant proposal section',
    evidence: 'need statements, evidence base, budget assumptions, and reviewer comments',
    asyncTask: 'Read a sample proposal and mark one evidence-strength issue',
    syncTask: 'Proposal workshop with peer review and revision planning',
    resource: 'sample proposal; budget worksheet; reviewer rubric',
    evaluation: 'Score need evidence, feasibility, budget logic, and feedback uptake',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'epidemiology methods sequence',
    courseName: 'Epidemiology Methods Sequence',
    lessonCount: 14,
    theme: 'epidemiology',
    lens: 'study design, measures of association, bias, confounding, and public health interpretation',
    artifact: 'epidemiology methods memo',
    evidence: 'study tables, risk ratios, bias checks, confounding notes, and interpretation limits',
    asyncTask: 'Review a study abstract and identify one validity threat',
    syncTask: 'Methods lab with calculation check and interpretation critique',
    resource: 'study abstract; 2x2 table; validity checklist',
    evaluation: 'Score design fit, calculation, bias reasoning, confounding, and interpretation',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'quizBank', 'studyGuides'],
    exportFeatureIds: ['syllabus', 'lessonPlans', 'quizBank'],
  }),
  scenario({
    name: 'supply chain case analytics',
    courseName: 'Supply Chain Case Analytics',
    lessonCount: 8,
    theme: 'supply chain analytics',
    lens: 'demand evidence, inventory constraints, logistics tradeoffs, and service risk',
    artifact: 'operations case brief',
    evidence: 'demand data, capacity constraints, inventory assumptions, and service-level tradeoffs',
    asyncTask: 'Review a demand table and mark one capacity risk',
    syncTask: 'Operations case lab with scenario comparison and recommendation',
    resource: 'case table; inventory model; recommendation template',
    evaluation: 'Score data interpretation, constraint reasoning, tradeoff analysis, and recommendation',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_caseBrief'],
    customFeatureIds: ['custom_caseBrief'],
  }),
  scenario({
    name: 'agile project management sprint',
    courseName: 'Agile Project Management Sprint',
    lessonCount: 8,
    theme: 'project management',
    lens: 'scope, backlog evidence, sprint planning, risk, and retrospective learning',
    artifact: 'sprint planning checkpoint',
    evidence: 'user stories, acceptance criteria, risk log, and retrospective notes',
    asyncTask: 'Review a backlog and identify one ambiguous acceptance criterion',
    syncTask: 'Sprint planning lab with estimation, risk review, and retro action',
    resource: 'backlog sample; risk log; retrospective template',
    evaluation: 'Score scope clarity, evidence, risk handling, and feedback-informed planning',
    featureIds: ['lessonPlans', 'assignments', 'courseFaq', 'custom_projectMilestone'],
    customFeatureIds: ['custom_projectMilestone'],
  }),
  scenario({
    name: 'pharmacy calculation safety',
    courseName: 'Pharmacy Calculation Safety',
    lessonCount: 8,
    theme: 'pharmacy calculations',
    lens: 'dosage setup, unit conversion, safety checks, and communication',
    artifact: 'calculation safety worksheet',
    evidence: 'unit setup, calculation trace, safety check, and communication note',
    asyncTask: 'Complete a low-stakes conversion check and mark one safety cue',
    syncTask: 'Calculation lab with peer verification and debrief',
    resource: 'practice calculation packet; safety checklist; unit conversion guide',
    evaluation: 'Score setup, calculation accuracy, safety reasoning, and verification',
    caution: 'Flag clinical safety requirements and local policy for human review.',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'quizBank', 'custom_problemSet'],
    customFeatureIds: ['custom_problemSet'],
  }),
  scenario({
    name: 'museum education design',
    courseName: 'Museum Education Design Studio',
    lessonCount: 8,
    theme: 'museum education',
    lens: 'visitor learning, object evidence, accessibility, and facilitation',
    artifact: 'gallery learning activity',
    evidence: 'object labels, visitor needs, accessibility considerations, and facilitation notes',
    asyncTask: 'Review an object record and identify one visitor question',
    syncTask: 'Gallery activity studio with peer facilitation and revision',
    resource: 'object record; facilitation guide; accessibility checklist',
    evaluation: 'Score object evidence, visitor fit, accessibility, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'second-language assessment design',
    courseName: 'Second-Language Assessment Design',
    lessonCount: 3,
    theme: 'language assessment',
    lens: 'proficiency evidence, task design, scoring criteria, and feedback',
    artifact: 'language assessment task',
    evidence: 'proficiency descriptors, task samples, scoring criteria, and feedback notes',
    asyncTask: 'Review a task sample and identify one validity issue',
    syncTask: 'Assessment design workshop with calibration and revision',
    resource: 'proficiency descriptors; sample task; scoring rubric',
    evaluation: 'Score construct fit, task clarity, scoring evidence, and feedback usefulness',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
  scenario({
    name: 'product analytics experiment design',
    courseName: 'Product Analytics Experiment Design',
    lessonCount: 8,
    theme: 'product analytics',
    lens: 'metrics, experiment validity, segmentation, and decision risk',
    artifact: 'experiment design memo',
    evidence: 'metric definitions, experiment assumptions, segment analysis, and decision thresholds',
    asyncTask: 'Review an experiment brief and mark one validity threat',
    syncTask: 'Analytics lab with metric critique and decision memo revision',
    resource: 'experiment brief; metric tree; decision memo model',
    evaluation: 'Score metric fit, validity, interpretation, and decision recommendation',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  }),
  scenario({
    name: 'nonprofit program evaluation',
    courseName: 'Nonprofit Program Evaluation',
    lessonCount: 8,
    theme: 'program evaluation',
    lens: 'logic models, indicators, mixed evidence, and stakeholder use',
    artifact: 'evaluation brief',
    evidence: 'logic-model links, indicator data, interview excerpts, and use recommendations',
    asyncTask: 'Review a logic model and identify one weak indicator',
    syncTask: 'Evaluation clinic with evidence triangulation and stakeholder feedback',
    resource: 'logic model; indicator table; interview excerpt packet',
    evaluation: 'Score indicator fit, evidence triangulation, validity limits, and use recommendation',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_policyMemo'],
    customFeatureIds: ['custom_policyMemo'],
  }),
  scenario({
    name: 'criminal justice policy seminar',
    courseName: 'Criminal Justice Policy Seminar',
    lessonCount: 8,
    theme: 'criminal justice policy',
    lens: 'legal context, empirical evidence, equity, and implementation',
    artifact: 'justice policy analysis memo',
    evidence: 'statutory excerpts, case evidence, empirical findings, and implementation limits',
    asyncTask: 'Read a policy excerpt and mark one empirical claim',
    syncTask: 'Seminar debate with evidence check and policy revision',
    resource: 'policy excerpt; empirical brief; equity checklist',
    evaluation: 'Score legal context, empirical evidence, equity reasoning, and feasibility',
    featureIds: ['syllabus', 'lessonPlans', 'assignments', 'discussions'],
  }),
  scenario({
    name: 'human computer interaction prototyping',
    courseName: 'Human-Computer Interaction Prototyping',
    lessonCount: 8,
    theme: 'interaction design',
    lens: 'user goals, prototype evidence, usability testing, and iteration',
    artifact: 'prototype test report',
    evidence: 'task flows, usability notes, failure points, and design recommendations',
    asyncTask: 'Review a prototype screen and identify one usability risk',
    syncTask: 'Usability test lab with observation coding and iteration planning',
    resource: 'prototype packet; usability script; observation checklist',
    evaluation: 'Score task fit, evidence trace, usability reasoning, and iteration',
    featureIds: ['lessonPlans', 'assignments', 'rubrics', 'custom_observationChecklist'],
    customFeatureIds: ['custom_observationChecklist'],
  }),
  scenario({
    name: 'comparative literature close reading',
    courseName: 'Comparative Literature Close Reading',
    lessonCount: 8,
    theme: 'close reading',
    lens: 'passage evidence, context, interpretation, and argument revision',
    artifact: 'close-reading response',
    evidence: 'passage details, context notes, interpretive claims, and counterreadings',
    asyncTask: 'Annotate a short passage and mark one interpretive tension',
    syncTask: 'Close-reading seminar with evidence comparison and revision',
    resource: 'passage packet; annotation model; response rubric',
    evaluation: 'Score textual evidence, interpretive precision, context restraint, and revision',
    featureIds: ['lessonPlans', 'assignments', 'discussions', 'custom_readingResponse'],
    customFeatureIds: ['custom_readingResponse'],
  }),
  scenario({
    name: 'digital marketing campaign lab',
    courseName: 'Digital Marketing Campaign Lab',
    lessonCount: 8,
    theme: 'digital marketing',
    lens: 'audience evidence, channel strategy, measurement, and campaign revision',
    artifact: 'campaign optimization brief',
    evidence: 'audience data, channel metrics, creative tests, and optimization rationale',
    asyncTask: 'Review a campaign dashboard and identify one metric risk',
    syncTask: 'Campaign lab with peer critique and optimization planning',
    resource: 'dashboard sample; persona brief; campaign checklist',
    evaluation: 'Score audience fit, metric interpretation, channel logic, and revision',
    featureIds: ['lessonPlans', 'assignments', 'quizBank', 'custom_feedbackForm'],
    customFeatureIds: ['custom_feedbackForm'],
  }),
];
