import React from 'react';
import Header from '../components/Header';

const LAST_UPDATED = 'July 13, 2026';

export default function TermsOfService() {
  return (
    <div className="min-h-screen mesh-bg noise-overlay">
      <Header compact />

      <main className="max-w-3xl mx-auto px-8 pb-16">
        <div className="mb-6">
          <h1 className="text-2xl font-extrabold tracking-tight text-slate-800">
            Terms of <span className="text-gradient">Service</span>
          </h1>
          <p className="text-slate-600 text-xs font-medium mt-1">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="glass panel-glow rounded-squircle shadow-glass p-8 space-y-6 text-sm text-slate-700 leading-relaxed">
          <Section title="Acceptance of Terms">
            <p>
              By using Course Mapper, you agree to these Terms of Service. If you do not agree, please do not use the
              tool. Course Mapper is provided by Tian Xing.
            </p>
          </Section>

          <Section title="Description of Service">
            <p>
              Course Mapper is a free, browser-based tool that uses artificial intelligence to help educators transform
              course syllabi into structured Course Map spreadsheets. The core tool is a static browser app with no
              Course Mapper-operated application backend.
            </p>
          </Section>

          <Section title="API Keys">
            <ul className="list-disc list-inside space-y-1.5 ml-1">
              <li>
                You may provide your own API key from OpenAI, Anthropic, Google, DeepSeek, or another supported
                provider. You are responsible for any costs incurred through your own API key usage.
              </li>
              <li>
                Scion requires no API key and runs a pinned public model in supported browsers. First use downloads
                approximately 3.35 GB of model weights from Hugging Face. Availability and speed depend on browser,
                device memory, storage, WebGPU support, and the public weight host.
              </li>
              <li>
                Course Mapper is not affiliated with OpenAI, Anthropic, Google, DeepSeek, or OpenRouter. Your use of
                their APIs is subject to their respective terms of service.
              </li>
            </ul>
          </Section>

          <Section title="AI-Generated Content">
            <p>
              Course maps generated by Course Mapper are AI-produced drafts. They are intended as a starting point for
              instructional design, not as final academic products.
            </p>
            <ul className="list-disc list-inside space-y-1.5 ml-1 mt-2">
              <li>
                <strong>No guarantee of accuracy.</strong> AI-generated content may contain errors, omissions, or
                fabricated information (including citations, resources, and tool names).
              </li>
              <li>
                <strong>Not a substitute for expertise.</strong> All generated content should be reviewed and revised by
                a qualified instructor before use in a course.
              </li>
              <li>
                <strong>No fact-checking.</strong> Course Mapper does not verify citations, validate resources, or check
                factual accuracy.
              </li>
              <li>
                <strong>Your responsibility.</strong> You are solely responsible for reviewing, editing, and approving
                any content before using it in an academic setting.
              </li>
            </ul>
          </Section>

          <Section title="Google Drive Integration">
            <p>
              Course Mapper's optional Google Drive export feature allows you to save files directly to your Google
              Drive account. By using this feature:
            </p>
            <ul className="list-disc list-inside space-y-1.5 ml-1 mt-2">
              <li>You authorize Course Mapper to create files in your Google Drive on your behalf.</li>
              <li>
                Course Mapper only requests permission to manage files it creates — it cannot access your other Drive
                files.
              </li>
              <li>
                You can revoke this permission at any time via your{' '}
                <a
                  href="https://myaccount.google.com/permissions"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-indigo-500 hover:text-indigo-700 underline"
                >
                  Google Account settings
                </a>
                .
              </li>
            </ul>
          </Section>

          <Section title="Intellectual Property">
            <ul className="list-disc list-inside space-y-1.5 ml-1">
              <li>
                <strong>Your content.</strong> You retain full ownership of your syllabus files, course maps, and any
                content you create or edit using Course Mapper.
              </li>
              <li>
                <strong>AI output.</strong> AI-generated content is provided to you for your use. Course Mapper makes no
                ownership claim over generated course maps.
              </li>
              <li>
                <strong>The tool.</strong> Course Mapper's source code, design, and branding are the property of Tian
                Xing.
              </li>
            </ul>
          </Section>

          <Section title="Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-1 mt-2">
              <li>Use Course Mapper for any unlawful purpose.</li>
              <li>Attempt to extract, misuse, or exfiltrate credentials, access tokens, or other private data.</li>
              <li>Use automation to abuse third-party services or violate provider rate limits and terms.</li>
              <li>
                Misrepresent AI-generated content as verified, peer-reviewed, or officially endorsed academic material.
              </li>
            </ul>
          </Section>

          <Section title="Disclaimer of Warranties">
            <p>
              Course Mapper is provided <strong>"as is"</strong> and <strong>"as available"</strong> without warranties
              of any kind, whether express or implied. We do not warrant that the tool will be uninterrupted,
              error-free, or that AI-generated content will be accurate or suitable for any particular purpose.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              To the fullest extent permitted by law, Tian Xing and Course Mapper contributors shall not be liable for
              any indirect, incidental, special, or consequential damages arising from your use of the tool, including
              but not limited to reliance on AI-generated content, loss of data, or API charges incurred through your
              own keys.
            </p>
          </Section>

          <Section title="Changes to Terms">
            <p>
              We may update these terms from time to time. Changes will be reflected on this page with an updated date.
              Continued use of Course Mapper after changes constitutes acceptance of the updated terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              For questions about these terms, contact Tian Xing at{' '}
              <a href="mailto:xingpicture@gmail.com" className="text-indigo-500 hover:text-indigo-700 underline">
                xingpicture@gmail.com
              </a>
              .
            </p>
          </Section>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 className="text-[15px] font-bold text-slate-800 mb-2 flex items-center gap-2">
        <div className="w-1.5 h-1.5 rounded-full bg-slate-400 dark:bg-slate-500" />
        {title}
      </h2>
      {children}
    </div>
  );
}
