import React from 'react';

const LAST_UPDATED = 'February 14, 2026';

export default function TermsOfService() {
  return (
    <div className="min-h-screen mesh-bg noise-overlay">
      <header className="relative pt-8 pb-6 px-8 max-w-3xl mx-auto w-full">
        <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-indigo-400/60 to-transparent" />
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <a href="#/" className="relative group">
              <div className="absolute -inset-1 bg-gradient-to-br from-indigo-500/20 to-violet-500/20 rounded-2xl blur-lg opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              <div className="relative w-10 h-10 rounded-[12px] bg-gradient-to-br from-indigo-500 via-violet-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
                <svg className="w-5 h-5 text-white/95" viewBox="0 0 24 24" fill="none">
                  <path d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5z" stroke="currentColor" strokeWidth={1.6} strokeLinecap="round"/>
                  <path d="M4 12a1 1 0 011-1h8a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1v-2z" stroke="currentColor" strokeWidth={1.6} strokeLinecap="round"/>
                  <path d="M4 19a1 1 0 011-1h5a1 1 0 011 1v1a1 1 0 01-1 1H5a1 1 0 01-1-1v-1z" stroke="currentColor" strokeWidth={1.6} strokeLinecap="round"/>
                  <path d="M19 14l-2 2 2 2" stroke="currentColor" strokeWidth={1.6} strokeLinecap="round" strokeLinejoin="round"/>
                  <circle cx="18" cy="18" r="1" fill="currentColor" opacity="0.6"/>
                </svg>
              </div>
            </a>
            <div>
              <h1 className="text-lg font-extrabold tracking-tight text-slate-800">
                Terms of <span className="text-gradient">Service</span>
              </h1>
              <p className="text-slate-400 text-[12px] font-medium mt-0.5">
                Last updated: {LAST_UPDATED}
              </p>
            </div>
          </div>
          <a
            href="#/"
            className="tactile group flex items-center gap-2 px-4 py-2 rounded-pill text-[11px] font-semibold text-slate-500 bg-white/50 border border-slate-200/40 hover:bg-white/70 hover:text-slate-700 shadow-glass hover:shadow-glass-lg transition-all duration-300"
          >
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to App
          </a>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-8 pb-16">
        <div className="glass panel-glow rounded-squircle shadow-glass p-8 space-y-6 text-sm text-slate-600 leading-relaxed">

          <Section title="Acceptance of Terms">
            <p>
              By using Course Mapper, you agree to these Terms of Service. If you do not agree, please
              do not use the tool. Course Mapper is provided by the Educational Technology team at NYU
              Silver School of Social Work.
            </p>
          </Section>

          <Section title="Description of Service">
            <p>
              Course Mapper is a free, browser-based tool that uses artificial intelligence to help
              educators transform course syllabi into structured Course Map spreadsheets. The tool runs
              entirely in your web browser with no backend server.
            </p>
          </Section>

          <Section title="Free Tier & API Keys">
            <ul className="list-disc list-inside space-y-1.5 ml-1">
              <li>Course Mapper offers a free tier powered by third-party AI providers. Free-tier models are shared among all users and subject to rate limits and availability.</li>
              <li>You may optionally provide your own API key from OpenAI, Anthropic, or Google. You are responsible for any costs incurred through your own API key usage.</li>
              <li>Course Mapper is not affiliated with OpenAI, Anthropic, Google, or OpenRouter. Your use of their APIs is subject to their respective terms of service.</li>
            </ul>
          </Section>

          <Section title="AI-Generated Content">
            <p>
              Course maps generated by Course Mapper are AI-produced drafts. They are intended as a
              starting point for instructional design, not as final academic products.
            </p>
            <ul className="list-disc list-inside space-y-1.5 ml-1 mt-2">
              <li><strong>No guarantee of accuracy.</strong> AI-generated content may contain errors, omissions, or fabricated information (including citations, resources, and tool names).</li>
              <li><strong>Not a substitute for expertise.</strong> All generated content should be reviewed and revised by a qualified instructor before use in a course.</li>
              <li><strong>No fact-checking.</strong> Course Mapper does not verify citations, validate resources, or check factual accuracy.</li>
              <li><strong>Your responsibility.</strong> You are solely responsible for reviewing, editing, and approving any content before using it in an academic setting.</li>
            </ul>
          </Section>

          <Section title="Google Drive Integration">
            <p>
              Course Mapper's optional Google Drive export feature allows you to save files directly
              to your Google Drive account. By using this feature:
            </p>
            <ul className="list-disc list-inside space-y-1.5 ml-1 mt-2">
              <li>You authorize Course Mapper to create files in your Google Drive on your behalf.</li>
              <li>Course Mapper only requests permission to manage files it creates — it cannot access your other Drive files.</li>
              <li>You can revoke this permission at any time via your <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="text-indigo-500 hover:text-indigo-700 underline">Google Account settings</a>.</li>
            </ul>
          </Section>

          <Section title="Intellectual Property">
            <ul className="list-disc list-inside space-y-1.5 ml-1">
              <li><strong>Your content.</strong> You retain full ownership of your syllabus files, course maps, and any content you create or edit using Course Mapper.</li>
              <li><strong>AI output.</strong> AI-generated content is provided to you for your use. Course Mapper makes no ownership claim over generated course maps.</li>
              <li><strong>The tool.</strong> Course Mapper's source code, design, and branding are the property of the development team at NYU Silver School of Social Work.</li>
            </ul>
          </Section>

          <Section title="Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-1 mt-2">
              <li>Use Course Mapper for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, extract, or misuse embedded API keys.</li>
              <li>Abuse the free tier by automated or excessive requests that degrade service for other users.</li>
              <li>Misrepresent AI-generated content as verified, peer-reviewed, or officially endorsed academic material.</li>
            </ul>
          </Section>

          <Section title="Disclaimer of Warranties">
            <p>
              Course Mapper is provided <strong>"as is"</strong> and <strong>"as available"</strong> without
              warranties of any kind, whether express or implied. We do not warrant that the tool will be
              uninterrupted, error-free, or that AI-generated content will be accurate or suitable for any
              particular purpose.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              To the fullest extent permitted by law, the Course Mapper team and NYU shall not be liable
              for any indirect, incidental, special, or consequential damages arising from your use of the
              tool, including but not limited to reliance on AI-generated content, loss of data, or API
              charges incurred through your own keys.
            </p>
          </Section>

          <Section title="Changes to Terms">
            <p>
              We may update these terms from time to time. Changes will be reflected on this page with an
              updated date. Continued use of Course Mapper after changes constitutes acceptance of the
              updated terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              For questions about these terms, contact the Educational Technology team at NYU Silver
              School of Social Work at{' '}
              <a href="mailto:edtech@nyu.edu" className="text-indigo-500 hover:text-indigo-700 underline">
                edtech@nyu.edu
              </a>.
            </p>
          </Section>

        </div>
      </main>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 className="text-[15px] font-bold text-slate-800 mb-2 flex items-center gap-2">
        <div className="w-1.5 h-1.5 rounded-full bg-indigo-500" />
        {title}
      </h2>
      {children}
    </div>
  );
}
