import { readFile, writeFile } from 'node:fs/promises';
import Ajv2020 from 'ajv/dist/2020.js';
import standalone from 'ajv/dist/standalone/index.js';
const base = new URL('../../src/lib/authoringCore/', import.meta.url);
const read = async (name) => JSON.parse(await readFile(new URL(`contracts/${name}`, base), 'utf8'));
const [lesson, request, catalog] = await Promise.all(
  ['lesson-bundle.schema.json', 'new-request.schema.json', 'tools.proposed.json'].map(read),
);
const ajv = new Ajv2020({ allErrors: true, strict: false, code: { source: true, esm: true } });
ajv.addSchema(lesson);
ajv.addSchema(request);
const exports = { lessonBundle: lesson.$id, newRequest: request.$id };
for (const [i, tool] of catalog.tools.entries()) {
  const schema = structuredClone(tool.inputSchema);
  if (schema.properties?.request) {
    delete schema.properties.request.$id;
    delete schema.properties.request.$schema;
  }
  const key = `urn:coursemapper:tool:${i}`;
  ajv.addSchema(schema, key);
  exports[`tool${i}`] = key;
}
let code = standalone(ajv, exports);
code = code.replace(
  /const (\w+) = require\("ajv\/dist\/runtime\/(\w+)"\)\.default;/g,
  (_, name, runtime) =>
    `import ${name}Module from 'ajv/dist/runtime/${runtime}.js'; const ${name} = ${name}Module.default || ${name}Module;`,
);
await writeFile(
  new URL('validators.generated.js', base),
  `// Generated by scripts/authoring/buildValidators.mjs. No runtime code generation.\n${code}\n`,
);
